/*  */

CREATE USER SHOWCASE_
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
PROFILE DEFAULT;

GRANT CONNECT TO SHOWCASE_;
GRANT RESOURCE TO SHOWCASE_;
GRANT CREATE ANY INDEX TO SHOWCASE_;
GRANT CREATE ANY TABLE TO SHOWCASE_;
GRANT CREATE TABLE TO SHOWCASE_;
GRANT CREATE USER TO SHOWCASE_;
GRANT CREATE VIEW TO SHOWCASE_;
GRANT EXECUTE ANY PROCEDURE TO SHOWCASE_;
GRANT UNLIMITED TABLESPACE TO SHOWCASE_;



