create sequence SEQ_EAV_SC_SHOWCASES_ID
/

create sequence SEQ_EAV_SC_SHOWCASES_PARENT_ID
/

create sequence SEQ_EAV_SC_SHOWCASE_FIELDS_ID
/

create sequence SEQ_R_CORE_CREDIT_HIS_ID
/

create sequence SEQ_R_CORE_CREDIT_ID
/

create sequence SEQ_R_CORE_PERSON_HIS_ID
/

create sequence SEQ_R_CORE_PERSON_ID
/

create sequence SEQ_R_CORE_DEBTOR_HIS_ID
/

create sequence SEQ_R_CORE_DEBTOR_ID
/

create sequence SEQ_R_CORE_ORG_AD_DOCS_HIS_ID
/

create sequence SEQ_R_CORE_ORG_D_NAMES_HIS_ID
/

create sequence SEQ_R_CORE_ORG_HEAD_DOCS_ID
/

create sequence SEQ_R_CORE_ORG_HEAD_NAMES_ID
/

create sequence SEQ_R_CORE_ORG_HIS_ID
/

create sequence SEQ_R_CORE_ORG_ID
/

create sequence SEQ_R_CORE_PERSON_ADDRESS_ID
/

create sequence SEQ_R_CORE_PERS_ADDRESS_HIS_ID
/

create sequence SEQ_R_CORE_ORG_ADDRESS_HIS_ID
/

create sequence SEQ_R_CORE_ORG_ADDRESS_ID
/

create sequence SEQ_R_CORE_ORG_CONTACTS_ID
/

create sequence SEQ_R_CORE_PERSON_CONTACTS_ID
/

create sequence SEQ_R_CORE_PERS_ONTACTS_HIS_ID
/

create sequence SEQ_R_CORE_ORG_CONTACTS_HIS_ID
/

create sequence SEQ_R_CORE_ORG_NAME_HIS_ID
/

create sequence SEQ_R_CORE_ORG_NAME_ID
/

create sequence SEQ_R_CORE_PERSON_DI_HIS_ID
/

create sequence SEQ_R_CORE_PERSON_DI_ID
/

create sequence SEQ_R_CORE_PERSON_NAME_HIS_ID
/

create sequence SEQ_R_CORE_PERSON_NAME_ID
/

create sequence SEQ_R_CORE_SUBJECT_DOC_HIS_ID
/

create sequence SEQ_R_CORE_SUBJECT_DOC_ID
/

create sequence SEQ_R_CORE_CREDIT_FLOW_ID
/

create sequence SEQ_R_CORE_ORG_DI_HIS_ID
/

create sequence SEQ_R_CORE_ORG_DI_ID
/

create sequence SEQ_R_CORE_PLEDGE_HIS_ID
/

create sequence SEQ_R_CORE_PLEDGE_ID
/

create sequence SEQ_R_CORE_REMAINS_ID
/

create sequence SEQ_R_CORE_TURNOVER_ID
/

create sequence SEQ_R_CORE_DELETE_LOG_ID
/

create sequence SEQ_R_CORE_PORT_IO_FLOW_KFN_ID
/

create sequence SEQ_R_CORE_PORT_O_FLOW_MSFO_ID
/

create sequence SEQ_R_CUST_REMAINS_VERT_ID
/

create sequence SEQ_R_REF_CREDITOR_HIS_ID
/

create sequence SEQ_R_REF_CREDITOR_ID
/

create sequence SEQ_R_REF_BALANCE_ACCOUNT_ID
/

create sequence SEQ_R_REF_BALAN_ACCOUNT_HIS_ID
/

create sequence SEQ_R_REF_BANK_RELATION_HIS_ID
/

create sequence SEQ_R_REF_BANK_RELATION_ID
/

create sequence SEQ_R_REF_CLASSIFICATION_ID
/

create sequence SEQ_R_REF_CLASS_ICATION_HIS_ID
/

create sequence SEQ_R_REF_CONTACT_TYPE_HIS_ID
/

create sequence SEQ_R_REF_CONTACT_TYPE_ID
/

create sequence SEQ_R_REF_COUNTRY_HIS_ID
/

create sequence SEQ_R_REF_COUNTRY_ID
/

create sequence SEQ_R_REF_CREDITOR_BRANCH_ID
/

create sequence SEQ_R_REF_CREDITOR_DOC_HIS_ID
/

create sequence SEQ_R_REF_CREDITOR_DOC_ID
/

create sequence SEQ_R_REF_CREDIT_OBJECT_HIS_ID
/

create sequence SEQ_R_REF_CREDIT_OBJECT_ID
/

create sequence SEQ_R_REF_CREDI_BRANCH_DOC_ID
/

create sequence SEQ_R_REF_CREDI_BRANCH_HIS_ID
/

create sequence SEQ_R_REF_CREDIT_PURPOSE_ID
/

create sequence SEQ_R_REF_CREDIT_TYPE_HIS_ID
/

create sequence SEQ_R_REF_CREDIT_TYPE_ID
/

create sequence SEQ_R_REF_CREDI_NCH_DOC_HIS_ID
/

create sequence SEQ_R_REF_CREDI_PURPOSE_HIS_ID
/

create sequence SEQ_R_REF_CURRENCY_HIS_ID
/

create sequence SEQ_R_REF_CURRENCY_ID
/

create sequence SEQ_R_REF_DEBTOR_TYPE_HIS_ID
/

create sequence SEQ_R_REF_DEBTOR_TYPE_ID
/

create sequence SEQ_R_REF_DOC_TYPE_HIS_ID
/

create sequence SEQ_R_REF_DOC_TYPE_ID
/

create sequence SEQ_R_REF_ECON_TRADE_HIS_ID
/

create sequence SEQ_R_REF_ECON_TRADE_ID
/

create sequence SEQ_R_REF_ENTERPRISE_TYPE_ID
/

create sequence SEQ_R_REF_ENTER_SE_TYPE_HIS_ID
/

create sequence SEQ_R_REF_FINANCE_SOURCE_ID
/

create sequence SEQ_R_REF_FINAN_SOURCE_HIS_ID
/

create sequence SEQ_R_REF_LEGAL_FORM_HIS_ID
/

create sequence SEQ_R_REF_LEGAL_FORM_ID
/

create sequence SEQ_R_REF_OFFSHORE_HIS_ID
/

create sequence SEQ_R_REF_OFFSHORE_ID
/

create sequence SEQ_R_REF_PLEDGE_TYPE_HIS_ID
/

create sequence SEQ_R_REF_PLEDGE_TYPE_ID
/

create sequence SEQ_R_REF_PORTFOLIO_HIS_ID
/

create sequence SEQ_R_REF_PORTFOLIO_ID
/

create sequence SEQ_R_REF_REGION_HIS_ID
/

create sequence SEQ_R_REF_REGION_ID
/

create sequence SEQ_R_REF_SUBJECT_TYPE_HIS_ID
/

create sequence SEQ_R_REF_SUBJECT_TYPE_ID
/

create table EAV_SC_SHOWCASES
(
	ID NUMBER(14) not null
		primary key,
	PARENT_ID NUMBER(14) not null,
	NAME VARCHAR2(128) not null,
	TABLE_NAME VARCHAR2(128),
	CLASS_NAME VARCHAR2(128) not null,
	DOWN_PATH VARCHAR2(128),
	IS_FINAL NUMBER(5) not null,
	IS_CHILD NUMBER(5) not null
)
/

create unique index ESS_UN_N
	on EAV_SC_SHOWCASES (NAME)
/

create trigger TRG_EAV_SC_SHOWCASES_ID
	before insert
	on EAV_SC_SHOWCASES
	for each row
BEGIN SELECT seq_eav_sc_showcases_id.nextval INTO :new.id FROM dual; END;
/

create trigger TRG_EAV_SC_SHOWCASES_PARENT_ID
	before insert
	on EAV_SC_SHOWCASES
	for each row
BEGIN SELECT seq_eav_sc_showcases_parent_id.nextval INTO :new.parent_id FROM dual; END;
/

create table EAV_SC_SHOWCASE_FIELDS
(
	ID NUMBER(14) not null
		primary key,
	SHOWCASE_ID NUMBER(14) not null,
	META_ID NUMBER(14) not null,
	ATTRIBUTE_ID NUMBER(14) not null,
	ATTRIBUTE_PATH VARCHAR2(128),
	COLUMN_NAME VARCHAR2(128) not null,
	TYPE NUMBER(5) not null
)
/

create trigger TRG_EAV_SC_SHOWCASE_FIELDS_ID
	before insert
	on EAV_SC_SHOWCASE_FIELDS
	for each row
BEGIN SELECT seq_eav_sc_showcase_fields_id.nextval INTO :new.id FROM dual; END;
/

create table R_CUST_REMAINS_VERT
(
	ID NUMBER(14) not null
		primary key,
	CREDIT_ID NUMBER(14) not null,
	VALUE NUMBER(17,3),
	CURR_VALUE NUMBER(17,3),
	TYPE_CODE VARCHAR2(1024),
	PASTDUE_OPEN_DATE DATE,
	PASTDUE_CLOSE_DATE DATE,
	WRITE_OFF_DATE DATE,
	CREDITOR_ID NUMBER(14),
	ACCOUNT_ID NUMBER(14),
	TYPE_ID NUMBER(14),
	CDC DATE,
	REP_DATE DATE
)
/

create trigger TRG_R_CUST_REMAINS_VERT_ID
	before insert
	on R_CUST_REMAINS_VERT
	for each row
BEGIN SELECT seq_R_CUST_REMAINS_VERT_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_CORE_CREDIT
(
	ID NUMBER(14) not null
		primary key,
	CREDIT_ID NUMBER(14) not null,
	CONTRACT_ID NUMBER(14),
	PRIMARY_CONTRACT_ID NUMBER(14),
	CREDIT_OBJECT_ID NUMBER(14),
	CREDIT_PURPOSE_ID NUMBER(14),
	CREDIT_TYPE_ID NUMBER(14),
	CURRENCY_ID NUMBER(14),
	FINANCE_SOURCE_ID NUMBER(14),
	PORTFOLIO_ID NUMBER(14),
	INNER_PORTFOLIO_ID NUMBER(14),
	PORTFOLIO_MSFO_ID NUMBER(14),
	AMOUNT NUMBER(17,3),
	ACTUAL_ISSUE_DATE DATE,
	CONTRACT_MATURITY_DATE DATE,
	HAS_CURRENCY_EARN NUMBER(1),
	INTEREST_RATE_YEARLY NUMBER(17,3),
	MATURITY_DATE DATE,
	PROLONGATION_DATE DATE,
	CREDITOR_ID NUMBER(14),
	CREDITOR_BRANCH_ID NUMBER(14),
	CREDITOR_CODE VARCHAR2(1024),
	CREDITOR_BRANCH_CODE VARCHAR2(1024),
	CONTRACT_NO VARCHAR2(1024),
	CONTRACT_DATE DATE,
	PRIMARY_CONTRACT_NO VARCHAR2(1024),
	PRIMARY_CONTRACT_DATE DATE,
	CREDIT_OBJECT_CODE VARCHAR2(1024),
	CREDIT_PURPOSE_CODE VARCHAR2(1024),
	CREDIT_TYPE_CODE VARCHAR2(1024),
	CURRENCY_CODE VARCHAR2(1024),
	FINANCE_SOURCE_CODE VARCHAR2(1024),
	PORTFOLIO_CODE VARCHAR2(1024),
	PORTFOLIO_MSFO_CODE VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index CC_IN_CI_43
	on R_CORE_CREDIT (CREDIT_ID, OPEN_DATE)
/

create trigger TRG_R_CORE_CREDIT_ID
	before insert
	on R_CORE_CREDIT
	for each row
BEGIN SELECT seq_R_CORE_CREDIT_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_CORE_CREDIT_HIS
(
	ID NUMBER(14) not null
		primary key,
	CREDIT_ID NUMBER(14) not null,
	CONTRACT_ID NUMBER(14),
	PRIMARY_CONTRACT_ID NUMBER(14),
	CREDIT_OBJECT_ID NUMBER(14),
	CREDIT_PURPOSE_ID NUMBER(14),
	CREDIT_TYPE_ID NUMBER(14),
	CURRENCY_ID NUMBER(14),
	FINANCE_SOURCE_ID NUMBER(14),
	PORTFOLIO_ID NUMBER(14),
	INNER_PORTFOLIO_ID NUMBER(14),
	PORTFOLIO_MSFO_ID NUMBER(14),
	AMOUNT NUMBER(17,3),
	ACTUAL_ISSUE_DATE DATE,
	CONTRACT_MATURITY_DATE DATE,
	HAS_CURRENCY_EARN NUMBER(1),
	INTEREST_RATE_YEARLY NUMBER(17,3),
	MATURITY_DATE DATE,
	PROLONGATION_DATE DATE,
	CREDITOR_ID NUMBER(14),
	CREDITOR_BRANCH_ID NUMBER(14),
	CREDITOR_CODE VARCHAR2(1024),
	CREDITOR_BRANCH_CODE VARCHAR2(1024),
	CONTRACT_NO VARCHAR2(1024),
	CONTRACT_DATE DATE,
	PRIMARY_CONTRACT_NO VARCHAR2(1024),
	PRIMARY_CONTRACT_DATE DATE,
	CREDIT_OBJECT_CODE VARCHAR2(1024),
	CREDIT_PURPOSE_CODE VARCHAR2(1024),
	CREDIT_TYPE_CODE VARCHAR2(1024),
	CURRENCY_CODE VARCHAR2(1024),
	FINANCE_SOURCE_CODE VARCHAR2(1024),
	PORTFOLIO_CODE VARCHAR2(1024),
	PORTFOLIO_MSFO_CODE VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index CC_IN_CI_43_HIS
	on R_CORE_CREDIT_HIS (CREDIT_ID, OPEN_DATE)
/

create trigger TRG_R_CORE_CREDIT_HIS_ID
	before insert
	on R_CORE_CREDIT_HIS
	for each row
BEGIN SELECT seq_R_CORE_CREDIT_HIS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_CORE_PERSON
(
	ID NUMBER(14) not null
		primary key,
	PERSON_INFO_ID NUMBER(14) not null,
	COUNTRY_ID NUMBER(14),
	OFFSHORE_ID NUMBER(14),
	COUNTRY_CODE VARCHAR2(1024),
	OFFSHORE_CODE VARCHAR2(1024),
	CREDITOR_ID NUMBER(14),
	SUBJECT_ID NUMBER(14),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index CP_IN_SI_17
	on R_CORE_PERSON (SUBJECT_ID, OPEN_DATE)
/

create trigger TRG_R_CORE_PERSON_ID
	before insert
	on R_CORE_PERSON
	for each row
BEGIN SELECT seq_R_CORE_PERSON_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_CORE_PERSON_HIS
(
	ID NUMBER(14) not null
		primary key,
	PERSON_INFO_ID NUMBER(14) not null,
	COUNTRY_ID NUMBER(14),
	OFFSHORE_ID NUMBER(14),
	COUNTRY_CODE VARCHAR2(1024),
	OFFSHORE_CODE VARCHAR2(1024),
	CREDITOR_ID NUMBER(14),
	SUBJECT_ID NUMBER(14),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index CP_IN_SI_17_HIS
	on R_CORE_PERSON_HIS (SUBJECT_ID, OPEN_DATE)
/

create trigger TRG_R_CORE_PERSON_HIS_ID
	before insert
	on R_CORE_PERSON_HIS
	for each row
BEGIN SELECT seq_R_CORE_PERSON_HIS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_CORE_ORG
(
	ID NUMBER(14) not null
		primary key,
	ORGANIZATION_INFO_ID NUMBER(14) not null,
	HEAD_ID NUMBER(14),
	IS_SE NUMBER(1),
	ECON_TRADE NUMBER(14),
	LEGAL_FORM NUMBER(14),
	OFFSHORE NUMBER(14),
	ENTERPRISE_TYPE NUMBER(14),
	COUNTRY NUMBER(14),
	CREDITOR_ID NUMBER(14),
	SUBJECT_ID NUMBER(14),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index CO_IN_SI_99
	on R_CORE_ORG (SUBJECT_ID, OPEN_DATE)
/

create trigger TRG_R_CORE_ORG_ID
	before insert
	on R_CORE_ORG
	for each row
BEGIN SELECT seq_R_CORE_ORG_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_CORE_ORG_HIS
(
	ID NUMBER(14) not null
		primary key,
	ORGANIZATION_INFO_ID NUMBER(14) not null,
	HEAD_ID NUMBER(14),
	IS_SE NUMBER(1),
	ECON_TRADE NUMBER(14),
	LEGAL_FORM NUMBER(14),
	OFFSHORE NUMBER(14),
	ENTERPRISE_TYPE NUMBER(14),
	COUNTRY NUMBER(14),
	CREDITOR_ID NUMBER(14),
	SUBJECT_ID NUMBER(14),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index CO_IN_SI_99_HIS
	on R_CORE_ORG_HIS (SUBJECT_ID, OPEN_DATE)
/

create trigger TRG_R_CORE_ORG_HIS_ID
	before insert
	on R_CORE_ORG_HIS
	for each row
BEGIN SELECT seq_R_CORE_ORG_HIS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_CORE_ORG_HEAD_NAMES
(
	ID NUMBER(14) not null
		primary key,
	HEAD_ID NUMBER(14) not null,
	NAME_ID NUMBER(14),
	FIRSTNAME VARCHAR2(1024),
	LASTNAME VARCHAR2(1024),
	MIDDLENAME VARCHAR2(1024),
	LANG VARCHAR2(1024),
	CREDITOR_ID NUMBER(14),
	SUBJECT_ID NUMBER(14),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index COHN_IN_NI_15
	on R_CORE_ORG_HEAD_NAMES (NAME_ID, OPEN_DATE)
/

create index COHN_IN_SI_NI_82
	on R_CORE_ORG_HEAD_NAMES (SUBJECT_ID, NAME_ID, OPEN_DATE)
/

create index COHN_IN_SI_63
	on R_CORE_ORG_HEAD_NAMES (SUBJECT_ID, OPEN_DATE)
/

create trigger TRG_R_CORE_ORG_HEAD_NAMES_ID
	before insert
	on R_CORE_ORG_HEAD_NAMES
	for each row
BEGIN SELECT seq_R_CORE_ORG_HEAD_NAMES_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_CORE_ORG_HEAD_NAMES_HIS
(
	ID NUMBER(14) not null
		primary key,
	HEAD_ID NUMBER(14) not null,
	NAME_ID NUMBER(14),
	FIRSTNAME VARCHAR2(1024),
	LASTNAME VARCHAR2(1024),
	MIDDLENAME VARCHAR2(1024),
	LANG VARCHAR2(1024),
	CREDITOR_ID NUMBER(14),
	SUBJECT_ID NUMBER(14),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index COHN_IN_NI_15_HIS
	on R_CORE_ORG_HEAD_NAMES_HIS (NAME_ID, OPEN_DATE)
/

create index COHN_IN_SI_NI_82_HIS
	on R_CORE_ORG_HEAD_NAMES_HIS (SUBJECT_ID, NAME_ID, OPEN_DATE)
/

create index COHN_IN_SI_63_HIS
	on R_CORE_ORG_HEAD_NAMES_HIS (SUBJECT_ID, OPEN_DATE)
/

create trigger TRG_R_CORE_ORG_D_NAMES_HIS_ID
	before insert
	on R_CORE_ORG_HEAD_NAMES_HIS
	for each row
BEGIN SELECT seq_R_CORE_ORG_D_NAMES_HIS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_CORE_ORG_HEAD_DOCS
(
	ID NUMBER(14) not null
		primary key,
	HEAD_ID NUMBER(14) not null,
	DOCUMENT_ID NUMBER(14),
	DOC_NO VARCHAR2(1024),
	DOC_TYPE_ID NUMBER(14),
	DOC_NAME VARCHAR2(1024),
	CREDITOR_ID NUMBER(14),
	SUBJECT_ID NUMBER(14),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index COHD_IN_DI_24
	on R_CORE_ORG_HEAD_DOCS (DOCUMENT_ID, OPEN_DATE)
/

create index COHD_IN_SI_DI_4
	on R_CORE_ORG_HEAD_DOCS (SUBJECT_ID, DOCUMENT_ID, OPEN_DATE)
/

create index COHD_IN_SI_28
	on R_CORE_ORG_HEAD_DOCS (SUBJECT_ID, OPEN_DATE)
/

create trigger TRG_R_CORE_ORG_HEAD_DOCS_ID
	before insert
	on R_CORE_ORG_HEAD_DOCS
	for each row
BEGIN SELECT seq_R_CORE_ORG_HEAD_DOCS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_CORE_ORG_HEAD_DOCS_HIS
(
	ID NUMBER(14) not null
		primary key,
	HEAD_ID NUMBER(14) not null,
	DOCUMENT_ID NUMBER(14),
	DOC_NO VARCHAR2(1024),
	DOC_TYPE_ID NUMBER(14),
	DOC_NAME VARCHAR2(1024),
	CREDITOR_ID NUMBER(14),
	SUBJECT_ID NUMBER(14),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index COHD_IN_DI_24_HIS
	on R_CORE_ORG_HEAD_DOCS_HIS (DOCUMENT_ID, OPEN_DATE)
/

create index COHD_IN_SI_DI_4_HIS
	on R_CORE_ORG_HEAD_DOCS_HIS (SUBJECT_ID, DOCUMENT_ID, OPEN_DATE)
/

create index COHD_IN_SI_28_HIS
	on R_CORE_ORG_HEAD_DOCS_HIS (SUBJECT_ID, OPEN_DATE)
/

create trigger TRG_R_CORE_ORG_AD_DOCS_HIS_ID
	before insert
	on R_CORE_ORG_HEAD_DOCS_HIS
	for each row
BEGIN SELECT seq_R_CORE_ORG_AD_DOCS_HIS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_CORE_DEBTOR
(
	ID NUMBER(14) not null
		primary key,
	SUBJECT_ID NUMBER(14) not null,
	IS_PERSON NUMBER(1),
	IS_ORGANIZATION NUMBER(1),
	IS_BANK_CREDITOR NUMBER(1),
	CREDITOR_ID NUMBER(14),
	CREDIT_ID NUMBER(14),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index CD_IN_CI_20
	on R_CORE_DEBTOR (CREDIT_ID, OPEN_DATE)
/

create trigger TRG_R_CORE_DEBTOR_ID
	before insert
	on R_CORE_DEBTOR
	for each row
BEGIN SELECT seq_R_CORE_DEBTOR_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_CORE_DEBTOR_HIS
(
	ID NUMBER(14) not null
		primary key,
	SUBJECT_ID NUMBER(14) not null,
	IS_PERSON NUMBER(1),
	IS_ORGANIZATION NUMBER(1),
	IS_BANK_CREDITOR NUMBER(1),
	CREDITOR_ID NUMBER(14),
	CREDIT_ID NUMBER(14),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index CD_IN_CI_20_HIS
	on R_CORE_DEBTOR_HIS (CREDIT_ID, OPEN_DATE)
/

create trigger TRG_R_CORE_DEBTOR_HIS_ID
	before insert
	on R_CORE_DEBTOR_HIS
	for each row
BEGIN SELECT seq_R_CORE_DEBTOR_HIS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_CORE_PERSON_ADDRESS
(
	ID NUMBER(14) not null
		primary key,
	PERSON_INFO_ID NUMBER(14) not null,
	ADDRESS_ID NUMBER(14),
	REGION_ID NUMBER(14),
	DETAILS VARCHAR2(1024),
	REGION_CODE VARCHAR2(1024),
	ADDRESS_TYPE VARCHAR2(1024),
	CREDITOR_ID NUMBER(14),
	SUBJECT_ID NUMBER(14),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index CPA_IN_AI_65
	on R_CORE_PERSON_ADDRESS (ADDRESS_ID, OPEN_DATE)
/

create index CPA_IN_SI_AI_14
	on R_CORE_PERSON_ADDRESS (SUBJECT_ID, ADDRESS_ID, OPEN_DATE)
/

create index CPA_IN_SI_12
	on R_CORE_PERSON_ADDRESS (SUBJECT_ID, OPEN_DATE)
/

create trigger TRG_R_CORE_PERSON_ADDRESS_ID
	before insert
	on R_CORE_PERSON_ADDRESS
	for each row
BEGIN SELECT seq_R_CORE_PERSON_ADDRESS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_CORE_PERSON_ADDRESS_HIS
(
	ID NUMBER(14) not null
		primary key,
	PERSON_INFO_ID NUMBER(14) not null,
	ADDRESS_ID NUMBER(14),
	REGION_ID NUMBER(14),
	DETAILS VARCHAR2(1024),
	REGION_CODE VARCHAR2(1024),
	ADDRESS_TYPE VARCHAR2(1024),
	CREDITOR_ID NUMBER(14),
	SUBJECT_ID NUMBER(14),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index CPA_IN_AI_65_HIS
	on R_CORE_PERSON_ADDRESS_HIS (ADDRESS_ID, OPEN_DATE)
/

create index CPA_IN_SI_AI_14_HIS
	on R_CORE_PERSON_ADDRESS_HIS (SUBJECT_ID, ADDRESS_ID, OPEN_DATE)
/

create index CPA_IN_SI_12_HIS
	on R_CORE_PERSON_ADDRESS_HIS (SUBJECT_ID, OPEN_DATE)
/

create trigger TRG_R_CORE_PERS_ADDRESS_HIS_ID
	before insert
	on R_CORE_PERSON_ADDRESS_HIS
	for each row
BEGIN SELECT seq_R_CORE_PERS_ADDRESS_HIS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_CORE_ORG_ADDRESS
(
	ID NUMBER(14) not null
		primary key,
	ORGANIZATION_INFO_ID NUMBER(14) not null,
	ADDRESS_ID NUMBER(14),
	REGION_ID NUMBER(14),
	DETAILS VARCHAR2(1024),
	REGION_CODE VARCHAR2(1024),
	ADDRESS_TYPE VARCHAR2(1024),
	CREDITOR_ID NUMBER(14),
	SUBJECT_ID NUMBER(14),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index COA_IN_AI_5
	on R_CORE_ORG_ADDRESS (ADDRESS_ID, OPEN_DATE)
/

create index COA_IN_SI_AI_60
	on R_CORE_ORG_ADDRESS (SUBJECT_ID, ADDRESS_ID, OPEN_DATE)
/

create index COA_IN_SI_53
	on R_CORE_ORG_ADDRESS (SUBJECT_ID, OPEN_DATE)
/

create trigger TRG_R_CORE_ORG_ADDRESS_ID
	before insert
	on R_CORE_ORG_ADDRESS
	for each row
BEGIN SELECT seq_R_CORE_ORG_ADDRESS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_CORE_ORG_ADDRESS_HIS
(
	ID NUMBER(14) not null
		primary key,
	ORGANIZATION_INFO_ID NUMBER(14) not null,
	ADDRESS_ID NUMBER(14),
	REGION_ID NUMBER(14),
	DETAILS VARCHAR2(1024),
	REGION_CODE VARCHAR2(1024),
	ADDRESS_TYPE VARCHAR2(1024),
	CREDITOR_ID NUMBER(14),
	SUBJECT_ID NUMBER(14),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index COA_IN_AI_5_HIS
	on R_CORE_ORG_ADDRESS_HIS (ADDRESS_ID, OPEN_DATE)
/

create index COA_IN_SI_AI_60_HIS
	on R_CORE_ORG_ADDRESS_HIS (SUBJECT_ID, ADDRESS_ID, OPEN_DATE)
/

create index COA_IN_SI_53_HIS
	on R_CORE_ORG_ADDRESS_HIS (SUBJECT_ID, OPEN_DATE)
/

create trigger TRG_R_CORE_ORG_ADDRESS_HIS_ID
	before insert
	on R_CORE_ORG_ADDRESS_HIS
	for each row
BEGIN SELECT seq_R_CORE_ORG_ADDRESS_HIS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_CORE_PERSON_CONTACTS
(
	ID NUMBER(14) not null
		primary key,
	PERSON_INFO_ID NUMBER(14) not null,
	CONTACT_ID NUMBER(14),
	CONTACT_TYPE_ID NUMBER(14),
	DETAILS_ID VARCHAR2(1024),
	DETAILS VARCHAR2(1024),
	CONTACT_TYPE_CODE VARCHAR2(1024),
	CREDITOR_ID NUMBER(14),
	SUBJECT_ID NUMBER(14),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index CPC_IN_CI_27
	on R_CORE_PERSON_CONTACTS (CONTACT_ID, OPEN_DATE)
/

create index CPC_IN_SI_CI_23
	on R_CORE_PERSON_CONTACTS (SUBJECT_ID, CONTACT_ID, OPEN_DATE)
/

create index CPC_IN_SI_63
	on R_CORE_PERSON_CONTACTS (SUBJECT_ID, OPEN_DATE)
/

create trigger TRG_R_CORE_PERSON_CONTACTS_ID
	before insert
	on R_CORE_PERSON_CONTACTS
	for each row
BEGIN SELECT seq_R_CORE_PERSON_CONTACTS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_CORE_PERSON_CONTACTS_HIS
(
	ID NUMBER(14) not null
		primary key,
	PERSON_INFO_ID NUMBER(14) not null,
	CONTACT_ID NUMBER(14),
	CONTACT_TYPE_ID NUMBER(14),
	DETAILS_ID VARCHAR2(1024),
	DETAILS VARCHAR2(1024),
	CONTACT_TYPE_CODE VARCHAR2(1024),
	CREDITOR_ID NUMBER(14),
	SUBJECT_ID NUMBER(14),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index CPC_IN_CI_27_HIS
	on R_CORE_PERSON_CONTACTS_HIS (CONTACT_ID, OPEN_DATE)
/

create index CPC_IN_SI_CI_23_HIS
	on R_CORE_PERSON_CONTACTS_HIS (SUBJECT_ID, CONTACT_ID, OPEN_DATE)
/

create index CPC_IN_SI_63_HIS
	on R_CORE_PERSON_CONTACTS_HIS (SUBJECT_ID, OPEN_DATE)
/

create trigger TRG_R_CORE_PERS_ONTACTS_HIS_ID
	before insert
	on R_CORE_PERSON_CONTACTS_HIS
	for each row
BEGIN SELECT seq_R_CORE_PERS_ONTACTS_HIS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_CORE_ORG_CONTACTS
(
	ID NUMBER(14) not null
		primary key,
	ORGANIZATION_INFO_ID NUMBER(14) not null,
	CONTACT_ID NUMBER(14),
	CONTACT_TYPE_ID NUMBER(14),
	DETAILS_ID VARCHAR2(1024),
	DETAILS VARCHAR2(1024),
	CONTACT_TYPE_CODE VARCHAR2(1024),
	CREDITOR_ID NUMBER(14),
	SUBJECT_ID NUMBER(14),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index COC_IN_CI_71
	on R_CORE_ORG_CONTACTS (CONTACT_ID, OPEN_DATE)
/

create index COC_IN_SI_CI_69
	on R_CORE_ORG_CONTACTS (SUBJECT_ID, CONTACT_ID, OPEN_DATE)
/

create index COC_IN_SI_33
	on R_CORE_ORG_CONTACTS (SUBJECT_ID, OPEN_DATE)
/

create trigger TRG_R_CORE_ORG_CONTACTS_ID
	before insert
	on R_CORE_ORG_CONTACTS
	for each row
BEGIN SELECT seq_R_CORE_ORG_CONTACTS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_CORE_ORG_CONTACTS_HIS
(
	ID NUMBER(14) not null
		primary key,
	ORGANIZATION_INFO_ID NUMBER(14) not null,
	CONTACT_ID NUMBER(14),
	CONTACT_TYPE_ID NUMBER(14),
	DETAILS_ID VARCHAR2(1024),
	DETAILS VARCHAR2(1024),
	CONTACT_TYPE_CODE VARCHAR2(1024),
	CREDITOR_ID NUMBER(14),
	SUBJECT_ID NUMBER(14),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index COC_IN_CI_71_HIS
	on R_CORE_ORG_CONTACTS_HIS (CONTACT_ID, OPEN_DATE)
/

create index COC_IN_SI_CI_69_HIS
	on R_CORE_ORG_CONTACTS_HIS (SUBJECT_ID, CONTACT_ID, OPEN_DATE)
/

create index COC_IN_SI_33_HIS
	on R_CORE_ORG_CONTACTS_HIS (SUBJECT_ID, OPEN_DATE)
/

create trigger TRG_R_CORE_ORG_CONTACTS_HIS_ID
	before insert
	on R_CORE_ORG_CONTACTS_HIS
	for each row
BEGIN SELECT seq_R_CORE_ORG_CONTACTS_HIS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_CORE_SUBJECT_DOC
(
	ID NUMBER(14) not null
		primary key,
	SUBJECT_ID NUMBER(14) not null,
	DOCUMENT_ID NUMBER(14),
	DOC_NO VARCHAR2(1024),
	DOC_TYPE NUMBER(14),
	DOC_NAME VARCHAR2(1024),
	CREDITOR_ID NUMBER(14),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index CSD_IN_SI_DI_42
	on R_CORE_SUBJECT_DOC (SUBJECT_ID, DOCUMENT_ID, OPEN_DATE)
/

create index CSD_IN_SI_42
	on R_CORE_SUBJECT_DOC (SUBJECT_ID, OPEN_DATE)
/

create index CSD_IN_DI_86
	on R_CORE_SUBJECT_DOC (DOCUMENT_ID, OPEN_DATE)
/

create trigger TRG_R_CORE_SUBJECT_DOC_ID
	before insert
	on R_CORE_SUBJECT_DOC
	for each row
BEGIN SELECT seq_R_CORE_SUBJECT_DOC_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_CORE_SUBJECT_DOC_HIS
(
	ID NUMBER(14) not null
		primary key,
	SUBJECT_ID NUMBER(14) not null,
	DOCUMENT_ID NUMBER(14),
	DOC_NO VARCHAR2(1024),
	DOC_TYPE NUMBER(14),
	DOC_NAME VARCHAR2(1024),
	CREDITOR_ID NUMBER(14),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index CSD_IN_SI_DI_42_HIS
	on R_CORE_SUBJECT_DOC_HIS (SUBJECT_ID, DOCUMENT_ID, OPEN_DATE)
/

create index CSD_IN_SI_42_HIS
	on R_CORE_SUBJECT_DOC_HIS (SUBJECT_ID, OPEN_DATE)
/

create index CSD_IN_DI_86_HIS
	on R_CORE_SUBJECT_DOC_HIS (DOCUMENT_ID, OPEN_DATE)
/

create trigger TRG_R_CORE_SUBJECT_DOC_HIS_ID
	before insert
	on R_CORE_SUBJECT_DOC_HIS
	for each row
BEGIN SELECT seq_R_CORE_SUBJECT_DOC_HIS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_CORE_PERSON_NAME
(
	ID NUMBER(14) not null
		primary key,
	PERSON_INFO_ID NUMBER(14) not null,
	NAME_ID NUMBER(14),
	FIRSTNAME VARCHAR2(1024),
	LASTNAME VARCHAR2(1024),
	MIDDLENAME VARCHAR2(1024),
	LANG VARCHAR2(1024),
	SUBJECT_ID NUMBER(14),
	CREDITOR_ID NUMBER(14),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index CPN_IN_NI_48
	on R_CORE_PERSON_NAME (NAME_ID, OPEN_DATE)
/

create index CPN_IN_SI_NI_10
	on R_CORE_PERSON_NAME (SUBJECT_ID, NAME_ID, OPEN_DATE)
/

create index CPN_IN_SI_33
	on R_CORE_PERSON_NAME (SUBJECT_ID, OPEN_DATE)
/

create trigger TRG_R_CORE_PERSON_NAME_ID
	before insert
	on R_CORE_PERSON_NAME
	for each row
BEGIN SELECT seq_R_CORE_PERSON_NAME_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_CORE_ORG_NAME
(
	ID NUMBER(14) not null
		primary key,
	ORGANIZATION_INFO_ID NUMBER(14) not null,
	NAME_ID NUMBER(14),
	NAME VARCHAR2(1024),
	LANG VARCHAR2(1024),
	CREDITOR_ID NUMBER(14),
	SUBJECT_ID NUMBER(14),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index CON_IN_NI_98
	on R_CORE_ORG_NAME (NAME_ID, OPEN_DATE)
/

create index CON_IN_SI_NI_82
	on R_CORE_ORG_NAME (SUBJECT_ID, NAME_ID, OPEN_DATE)
/

create index CON_IN_SI_74
	on R_CORE_ORG_NAME (SUBJECT_ID, OPEN_DATE)
/

create trigger TRG_R_CORE_ORG_NAME_ID
	before insert
	on R_CORE_ORG_NAME
	for each row
BEGIN SELECT seq_R_CORE_ORG_NAME_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_CORE_PERSON_NAME_HIS
(
	ID NUMBER(14) not null
		primary key,
	PERSON_INFO_ID NUMBER(14) not null,
	NAME_ID NUMBER(14),
	FIRSTNAME VARCHAR2(1024),
	LASTNAME VARCHAR2(1024),
	MIDDLENAME VARCHAR2(1024),
	LANG VARCHAR2(1024),
	SUBJECT_ID NUMBER(14),
	CREDITOR_ID NUMBER(14),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index CPN_IN_NI_48_HIS
	on R_CORE_PERSON_NAME_HIS (NAME_ID, OPEN_DATE)
/

create index CPN_IN_SI_NI_10_HIS
	on R_CORE_PERSON_NAME_HIS (SUBJECT_ID, NAME_ID, OPEN_DATE)
/

create index CPN_IN_SI_33_HIS
	on R_CORE_PERSON_NAME_HIS (SUBJECT_ID, OPEN_DATE)
/

create trigger TRG_R_CORE_PERSON_NAME_HIS_ID
	before insert
	on R_CORE_PERSON_NAME_HIS
	for each row
BEGIN SELECT seq_R_CORE_PERSON_NAME_HIS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_CORE_ORG_NAME_HIS
(
	ID NUMBER(14) not null
		primary key,
	ORGANIZATION_INFO_ID NUMBER(14) not null,
	NAME_ID NUMBER(14),
	NAME VARCHAR2(1024),
	LANG VARCHAR2(1024),
	CREDITOR_ID NUMBER(14),
	SUBJECT_ID NUMBER(14),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index CON_IN_NI_98_HIS
	on R_CORE_ORG_NAME_HIS (NAME_ID, OPEN_DATE)
/

create index CON_IN_SI_NI_82_HIS
	on R_CORE_ORG_NAME_HIS (SUBJECT_ID, NAME_ID, OPEN_DATE)
/

create index CON_IN_SI_74_HIS
	on R_CORE_ORG_NAME_HIS (SUBJECT_ID, OPEN_DATE)
/

create trigger TRG_R_CORE_ORG_NAME_HIS_ID
	before insert
	on R_CORE_ORG_NAME_HIS
	for each row
BEGIN SELECT seq_R_CORE_ORG_NAME_HIS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_CORE_PERSON_DI
(
	ID NUMBER(14) not null
		primary key,
	PERSON_INFO_ID NUMBER(14) not null,
	PERSON_BANK_RELATION_ID NUMBER(14),
	REF_BANK_RELATION_ID NUMBER(14),
	BANK_RELATION_CREDITOR_ID NUMBER(14),
	CREDITOR_ID NUMBER(14),
	SUBJECT_ID NUMBER(14),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index CPD_IN_PBRI_53
	on R_CORE_PERSON_DI (PERSON_BANK_RELATION_ID, OPEN_DATE)
/

create index CPD_IN_SI_PBRI_53
	on R_CORE_PERSON_DI (SUBJECT_ID, PERSON_BANK_RELATION_ID, OPEN_DATE)
/

create index CPD_IN_SI_35
	on R_CORE_PERSON_DI (SUBJECT_ID, OPEN_DATE)
/

create trigger TRG_R_CORE_PERSON_DI_ID
	before insert
	on R_CORE_PERSON_DI
	for each row
BEGIN SELECT seq_R_CORE_PERSON_DI_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_CORE_PERSON_DI_HIS
(
	ID NUMBER(14) not null
		primary key,
	PERSON_INFO_ID NUMBER(14) not null,
	PERSON_BANK_RELATION_ID NUMBER(14),
	REF_BANK_RELATION_ID NUMBER(14),
	BANK_RELATION_CREDITOR_ID NUMBER(14),
	CREDITOR_ID NUMBER(14),
	SUBJECT_ID NUMBER(14),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index CPD_IN_PBRI_53_HIS
	on R_CORE_PERSON_DI_HIS (PERSON_BANK_RELATION_ID, OPEN_DATE)
/

create index CPD_IN_SI_PBRI_53_HIS
	on R_CORE_PERSON_DI_HIS (SUBJECT_ID, PERSON_BANK_RELATION_ID, OPEN_DATE)
/

create index CPD_IN_SI_35_HIS
	on R_CORE_PERSON_DI_HIS (SUBJECT_ID, OPEN_DATE)
/

create trigger TRG_R_CORE_PERSON_DI_HIS_ID
	before insert
	on R_CORE_PERSON_DI_HIS
	for each row
BEGIN SELECT seq_R_CORE_PERSON_DI_HIS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_CORE_ORG_DI
(
	ID NUMBER(14) not null
		primary key,
	ORGANIZATION_INFO_ID NUMBER(14) not null,
	ORG_BANK_RELATION_ID NUMBER(14),
	REF_BANK_RELATION_ID NUMBER(14),
	BANK_RELATION_CREDITOR_ID NUMBER(14),
	CREDITOR_ID NUMBER(14),
	SUBJECT_ID NUMBER(14),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index COD_IN_OBRI_74
	on R_CORE_ORG_DI (ORG_BANK_RELATION_ID, OPEN_DATE)
/

create index COD_IN_SI_OBRI_51
	on R_CORE_ORG_DI (SUBJECT_ID, ORG_BANK_RELATION_ID, OPEN_DATE)
/

create index COD_IN_SI_87
	on R_CORE_ORG_DI (SUBJECT_ID, OPEN_DATE)
/

create trigger TRG_R_CORE_ORG_DI_ID
	before insert
	on R_CORE_ORG_DI
	for each row
BEGIN SELECT seq_R_CORE_ORG_DI_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_CORE_ORG_DI_HIS
(
	ID NUMBER(14) not null
		primary key,
	ORGANIZATION_INFO_ID NUMBER(14) not null,
	ORG_BANK_RELATION_ID NUMBER(14),
	REF_BANK_RELATION_ID NUMBER(14),
	BANK_RELATION_CREDITOR_ID NUMBER(14),
	CREDITOR_ID NUMBER(14),
	SUBJECT_ID NUMBER(14),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index COD_IN_OBRI_74_HIS
	on R_CORE_ORG_DI_HIS (ORG_BANK_RELATION_ID, OPEN_DATE)
/

create index COD_IN_SI_OBRI_51_HIS
	on R_CORE_ORG_DI_HIS (SUBJECT_ID, ORG_BANK_RELATION_ID, OPEN_DATE)
/

create index COD_IN_SI_87_HIS
	on R_CORE_ORG_DI_HIS (SUBJECT_ID, OPEN_DATE)
/

create trigger TRG_R_CORE_ORG_DI_HIS_ID
	before insert
	on R_CORE_ORG_DI_HIS
	for each row
BEGIN SELECT seq_R_CORE_ORG_DI_HIS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_CORE_TURNOVER
(
	ID NUMBER(14) not null
		primary key,
	CHANGE_ID NUMBER(14) not null,
	TURNOVER_ID NUMBER(14),
	ISSUE_ID NUMBER(14),
	DEBT_ID NUMBER(14),
	INTEREST_ID NUMBER(14),
	DEBT_AMOUNT NUMBER(17,3),
	DEBT_AMOUNT_CURRENCY NUMBER(17,3),
	INTEREST_AMOUNT NUMBER(17,3),
	INTEREST_AMOUNT_CURRENCY NUMBER(17,3),
	CREDITOR_ID NUMBER(14),
	CREDIT_ID NUMBER(14),
	CDC DATE,
	REP_DATE DATE
)
/

create index CT_IN_CI_55
	on R_CORE_TURNOVER (CREDIT_ID, REP_DATE)
/

create trigger TRG_R_CORE_TURNOVER_ID
	before insert
	on R_CORE_TURNOVER
	for each row
BEGIN SELECT seq_R_CORE_TURNOVER_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_CORE_CREDIT_FLOW
(
	ID NUMBER(14) not null
		primary key,
	CHANGE_ID NUMBER(14) not null,
	CREDIT_FLOW_ID NUMBER(14),
	CLASSIFICATION_ID NUMBER(14),
	PROVISION_ID NUMBER(14),
	PROVISION_KFN_ID NUMBER(14),
	PROVISION_MSFO_ID NUMBER(14),
	PROVISION_MSFO_OB_ID NUMBER(14),
	KFN_BALANCE_ACCOUNT_ID NUMBER(14),
	KFN_VALUE NUMBER(17,3),
	MSFO_BALANCE_ACCOUNT_ID NUMBER(14),
	MSFO_VALUE NUMBER(17,3),
	MSFO_OB_BALANCE_ACCOUNT_ID NUMBER(14),
	MSFO_OB_VALUE NUMBER(17,3),
	CREDITOR_ID NUMBER(14),
	CREDIT_ID NUMBER(14),
	CDC DATE,
	REP_DATE DATE
)
/

create index CCF_IN_CI_20
	on R_CORE_CREDIT_FLOW (CREDIT_ID, REP_DATE)
/

create trigger TRG_R_CORE_CREDIT_FLOW_ID
	before insert
	on R_CORE_CREDIT_FLOW
	for each row
BEGIN SELECT seq_R_CORE_CREDIT_FLOW_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_CORE_PLEDGE
(
	ID NUMBER(14) not null
		primary key,
	PLEDGE_ID NUMBER(14) not null,
	PLEDGE_TYPE NUMBER(14),
	CONTRACT VARCHAR2(1024),
	VALUE NUMBER(17,3),
	CREDITOR_ID NUMBER(14),
	CREDIT_ID NUMBER(14),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index CP_IN_CI_65
	on R_CORE_PLEDGE (CREDIT_ID, OPEN_DATE)
/

create trigger TRG_R_CORE_PLEDGE_ID
	before insert
	on R_CORE_PLEDGE
	for each row
BEGIN SELECT seq_R_CORE_PLEDGE_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_CORE_PLEDGE_HIS
(
	ID NUMBER(14) not null
		primary key,
	PLEDGE_ID NUMBER(14) not null,
	PLEDGE_TYPE NUMBER(14),
	CONTRACT VARCHAR2(1024),
	VALUE NUMBER(17,3),
	CREDITOR_ID NUMBER(14),
	CREDIT_ID NUMBER(14),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index CP_IN_CI_65_HIS
	on R_CORE_PLEDGE_HIS (CREDIT_ID, OPEN_DATE)
/

create trigger TRG_R_CORE_PLEDGE_HIS_ID
	before insert
	on R_CORE_PLEDGE_HIS
	for each row
BEGIN SELECT seq_R_CORE_PLEDGE_HIS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_CORE_REMAINS
(
	ID NUMBER(14) not null
		primary key,
	CHANGE_ID NUMBER(14) not null,
	REMAINS_ID NUMBER(14),
	LIMIT_ID NUMBER(14),
	BA_LIMIT_ID NUMBER(14),
	INTEREST_ID NUMBER(14),
	INTEREST_CURRENT_ID NUMBER(14),
	BA_INTEREST_CURRENT_ID NUMBER(14),
	INTEREST_PASTDUE_ID NUMBER(14),
	BA_INTEREST_PASTDUE_ID NUMBER(14),
	INTEREST_WRITE_OFF_ID NUMBER(14),
	DEBT_ID NUMBER(14),
	DEBT_CURRENT_ID NUMBER(14),
	BA_DEBT_CURRENT_ID NUMBER(14),
	DEBT_PASTDUE_ID NUMBER(14),
	BA_DEBT_PASTDUE_ID NUMBER(14),
	DEBT_WRITE_OFF_ID NUMBER(14),
	BA_DEBT_WRT_ID NUMBER(14),
	DISCOUNT_ID NUMBER(14),
	BA_DISCOUNT_ID NUMBER(14),
	DISCOUNTED_VALUE_ID NUMBER(14),
	CORRECTION_ID NUMBER(14),
	BA_CORRECTION_ID NUMBER(14),
	LIMIT_VALUE NUMBER(17,3),
	LIMIT_CVALUE NUMBER(17,3),
	INTEREST_CURRENT_VALUE NUMBER(17,3),
	INTEREST_CURRENT_CVALUE NUMBER(17,3),
	INTEREST_PASTDUE_VALUE NUMBER(17,3),
	INTEREST_PASTDUE_CVALUE NUMBER(17,3),
	INTEREST_PASTDUE_OPEN_DATE DATE,
	INTEREST_PASTDUE_CLOSE_DATE DATE,
	INTEREST_WRT_DATE DATE,
	INTEREST_WRT_VALUE NUMBER(17,3),
	INTEREST_WRT_CVALUE NUMBER(17,3),
	DEBT_CURRENT_VALUE NUMBER(17,3),
	DEBT_CURRENT_CVALUE NUMBER(17,3),
	DEBT_PASTDUE_VALUE NUMBER(17,3),
	DEBT_PASTDUE_CVALUE NUMBER(17,3),
	DEBT_PASTDUE_OPEN_DATE DATE,
	DEBT_PASTDUE_CLOSE_DATE DATE,
	DEBT_WRT_VALUE NUMBER(17,3),
	DEBT_WRT_CVALUE NUMBER(17,3),
	DEBT_WRT_DATE DATE,
	DEBT_DISCOUNT_VALUE NUMBER(17,3),
	DEBT_DISCOUNT_CVALUE NUMBER(17,3),
	DISCOUNTED_VALUE NUMBER(17,3),
	CORR_VALUE NUMBER(17,3),
	CORR_CVALUE NUMBER(17,3),
	CREDITOR_ID NUMBER(14),
	CREDIT_ID NUMBER(14),
	CDC DATE,
	REP_DATE DATE
)
/

create index CR_IN_CI_89
	on R_CORE_REMAINS (CREDIT_ID, REP_DATE)
/

create trigger TRG_R_CORE_REMAINS_ID
	before insert
	on R_CORE_REMAINS
	for each row
BEGIN SELECT seq_R_CORE_REMAINS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_CORE_PORTFOLIO_FLOW_KFN
(
	ID NUMBER(14) not null
		primary key,
	PORTFOLIO_FLOW_KFN_ID NUMBER(14) not null,
	PORTFOLIO_ID NUMBER(14),
	PORTFOLIO_CREDITOR_ID NUMBER(14),
	DETAILS_ID NUMBER(14),
	BALANCE_ACCOUNT_ID NUMBER(14),
	VALUE NUMBER(17,3),
	PORTFOLIO_DATA_ID NUMBER(14),
	PORTFOLIO_DATA_CREDITOR_ID NUMBER(14),
	CDC DATE,
	REP_DATE DATE
)
/

create index CPFK_IN_PDI_PFKI_DI_62
	on R_CORE_PORTFOLIO_FLOW_KFN (PORTFOLIO_DATA_ID, PORTFOLIO_FLOW_KFN_ID, DETAILS_ID, REP_DATE)
/

create index CPFK_IN_PDI_PFKI_77
	on R_CORE_PORTFOLIO_FLOW_KFN (PORTFOLIO_DATA_ID, PORTFOLIO_FLOW_KFN_ID, REP_DATE)
/

create index CPFK_IN_PDI_73
	on R_CORE_PORTFOLIO_FLOW_KFN (PORTFOLIO_DATA_ID, REP_DATE)
/

create trigger TRG_R_CORE_PORT_IO_FLOW_KFN_ID
	before insert
	on R_CORE_PORTFOLIO_FLOW_KFN
	for each row
BEGIN SELECT seq_R_CORE_PORT_IO_FLOW_KFN_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_CORE_PORTFOLIO_FLOW_MSFO
(
	ID NUMBER(14) not null
		primary key,
	PORTFOLIO_FLOW_MSFO_ID NUMBER(14) not null,
	DETAILS_ID NUMBER(14),
	PORTFOLIO_ID NUMBER(14),
	BALANCE_ACCOUNT_ID NUMBER(14),
	PORTFOLIO_CREDITOR_ID NUMBER(14),
	VALUE NUMBER(17,3),
	DISCOUNTED_VALUE NUMBER(17,3),
	PORTFOLIO_DATA_ID NUMBER(14),
	PORTFOLIO_DATA_CREDITOR_ID NUMBER(14),
	CDC DATE,
	REP_DATE DATE
)
/

create index CPFM_IN_PDI_PFMI_DI_8
	on R_CORE_PORTFOLIO_FLOW_MSFO (PORTFOLIO_DATA_ID, PORTFOLIO_FLOW_MSFO_ID, DETAILS_ID, REP_DATE)
/

create index CPFM_IN_PDI_PFMI_67
	on R_CORE_PORTFOLIO_FLOW_MSFO (PORTFOLIO_DATA_ID, PORTFOLIO_FLOW_MSFO_ID, REP_DATE)
/

create index CPFM_IN_PDI_33
	on R_CORE_PORTFOLIO_FLOW_MSFO (PORTFOLIO_DATA_ID, REP_DATE)
/

create trigger TRG_R_CORE_PORT_O_FLOW_MSFO_ID
	before insert
	on R_CORE_PORTFOLIO_FLOW_MSFO
	for each row
BEGIN SELECT seq_R_CORE_PORT_O_FLOW_MSFO_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_CORE_DELETE_LOG
(
	ID NUMBER(14) not null
		primary key,
	CREDIT_ID NUMBER(14) not null,
	CREDITOR_ID NUMBER(14),
	CDC DATE,
	REP_DATE DATE
)
/

create index CDL_IN_CI_56
	on R_CORE_DELETE_LOG (CREDIT_ID, REP_DATE)
/

create trigger TRG_R_CORE_DELETE_LOG_ID
	before insert
	on R_CORE_DELETE_LOG
	for each row
BEGIN SELECT seq_R_CORE_DELETE_LOG_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_CREDITOR
(
	ID NUMBER(14) not null
		primary key,
	REF_CREDITOR_ID NUMBER(14) not null,
	SUBJECT_TYPE_ID NUMBER(14),
	CODE VARCHAR2(1024),
	NAME VARCHAR2(1024),
	NOKBDB_CODE VARCHAR2(1024),
	SHORT_NAME VARCHAR2(1024),
	SUBJECT_TYPE_CODE VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RC_IN_RCI_87
	on R_REF_CREDITOR (REF_CREDITOR_ID, OPEN_DATE)
/

create trigger TRG_R_REF_CREDITOR_ID
	before insert
	on R_REF_CREDITOR
	for each row
BEGIN SELECT seq_R_REF_CREDITOR_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_CREDITOR_HIS
(
	ID NUMBER(14) not null
		primary key,
	REF_CREDITOR_ID NUMBER(14) not null,
	SUBJECT_TYPE_ID NUMBER(14),
	CODE VARCHAR2(1024),
	NAME VARCHAR2(1024),
	NOKBDB_CODE VARCHAR2(1024),
	SHORT_NAME VARCHAR2(1024),
	SUBJECT_TYPE_CODE VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RC_IN_RCI_87_HIS
	on R_REF_CREDITOR_HIS (REF_CREDITOR_ID, OPEN_DATE)
/

create trigger TRG_R_REF_CREDITOR_HIS_ID
	before insert
	on R_REF_CREDITOR_HIS
	for each row
BEGIN SELECT seq_R_REF_CREDITOR_HIS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_BALANCE_ACCOUNT
(
	ID NUMBER(14) not null
		primary key,
	REF_BALANCE_ACCOUNT_ID NUMBER(14) not null,
	DISPLAY_NO VARCHAR2(1024),
	FIFTH_SIGN VARCHAR2(1024),
	FIRST_FOURTH_SIGNS VARCHAR2(1024),
	IS_IN_BALANCE NUMBER(1),
	NAME_KZ VARCHAR2(1024),
	NAME_RU VARCHAR2(1024),
	NO_ VARCHAR2(1024),
	SEVENTH_SIGN VARCHAR2(1024),
	SIXTH_SIGN VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RBA_IN_RBAI_67
	on R_REF_BALANCE_ACCOUNT (REF_BALANCE_ACCOUNT_ID, OPEN_DATE)
/

create trigger TRG_R_REF_BALANCE_ACCOUNT_ID
	before insert
	on R_REF_BALANCE_ACCOUNT
	for each row
BEGIN SELECT seq_R_REF_BALANCE_ACCOUNT_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_BALANCE_ACCOUNT_HIS
(
	ID NUMBER(14) not null
		primary key,
	REF_BALANCE_ACCOUNT_ID NUMBER(14) not null,
	DISPLAY_NO VARCHAR2(1024),
	FIFTH_SIGN VARCHAR2(1024),
	FIRST_FOURTH_SIGNS VARCHAR2(1024),
	IS_IN_BALANCE NUMBER(1),
	NAME_KZ VARCHAR2(1024),
	NAME_RU VARCHAR2(1024),
	NO_ VARCHAR2(1024),
	SEVENTH_SIGN VARCHAR2(1024),
	SIXTH_SIGN VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RBA_IN_RBAI_67_HIS
	on R_REF_BALANCE_ACCOUNT_HIS (REF_BALANCE_ACCOUNT_ID, OPEN_DATE)
/

create trigger TRG_R_REF_BALAN_ACCOUNT_HIS_ID
	before insert
	on R_REF_BALANCE_ACCOUNT_HIS
	for each row
BEGIN SELECT seq_R_REF_BALAN_ACCOUNT_HIS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_BANK_RELATION
(
	ID NUMBER(14) not null
		primary key,
	REF_BANK_RELATION_ID NUMBER(14) not null,
	CODE VARCHAR2(1024),
	NAME_KZ VARCHAR2(1024),
	NAME_RU VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RBR_IN_RBRI_71
	on R_REF_BANK_RELATION (REF_BANK_RELATION_ID, OPEN_DATE)
/

create trigger TRG_R_REF_BANK_RELATION_ID
	before insert
	on R_REF_BANK_RELATION
	for each row
BEGIN SELECT seq_R_REF_BANK_RELATION_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_BANK_RELATION_HIS
(
	ID NUMBER(14) not null
		primary key,
	REF_BANK_RELATION_ID NUMBER(14) not null,
	CODE VARCHAR2(1024),
	NAME_KZ VARCHAR2(1024),
	NAME_RU VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RBR_IN_RBRI_71_HIS
	on R_REF_BANK_RELATION_HIS (REF_BANK_RELATION_ID, OPEN_DATE)
/

create trigger TRG_R_REF_BANK_RELATION_HIS_ID
	before insert
	on R_REF_BANK_RELATION_HIS
	for each row
BEGIN SELECT seq_R_REF_BANK_RELATION_HIS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_CLASSIFICATION
(
	ID NUMBER(14) not null
		primary key,
	REF_CLASSIFICATION_ID NUMBER(14) not null,
	CODE VARCHAR2(1024),
	COMMENT_KZ VARCHAR2(1024),
	COMMENT_RU VARCHAR2(1024),
	IS_INPUT_VALUE NUMBER(1),
	NAME_KZ VARCHAR2(1024),
	NAME_RU VARCHAR2(1024),
	PROVISION_DEBT NUMBER(17,3),
	PROVISION_PORTFOLIO_MAX NUMBER(17,3),
	PROVISION_PORTFOLIO_MIN NUMBER(17,3),
	VALUE_ NUMBER(17,3),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RC_IN_RCI_66
	on R_REF_CLASSIFICATION (REF_CLASSIFICATION_ID, OPEN_DATE)
/

create trigger TRG_R_REF_CLASSIFICATION_ID
	before insert
	on R_REF_CLASSIFICATION
	for each row
BEGIN SELECT seq_R_REF_CLASSIFICATION_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_CLASSIFICATION_HIS
(
	ID NUMBER(14) not null
		primary key,
	REF_CLASSIFICATION_ID NUMBER(14) not null,
	CODE VARCHAR2(1024),
	COMMENT_KZ VARCHAR2(1024),
	COMMENT_RU VARCHAR2(1024),
	IS_INPUT_VALUE NUMBER(1),
	NAME_KZ VARCHAR2(1024),
	NAME_RU VARCHAR2(1024),
	PROVISION_DEBT NUMBER(17,3),
	PROVISION_PORTFOLIO_MAX NUMBER(17,3),
	PROVISION_PORTFOLIO_MIN NUMBER(17,3),
	VALUE_ NUMBER(17,3),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RC_IN_RCI_66_HIS
	on R_REF_CLASSIFICATION_HIS (REF_CLASSIFICATION_ID, OPEN_DATE)
/

create trigger TRG_R_REF_CLASS_ICATION_HIS_ID
	before insert
	on R_REF_CLASSIFICATION_HIS
	for each row
BEGIN SELECT seq_R_REF_CLASS_ICATION_HIS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_CONTACT_TYPE
(
	ID NUMBER(14) not null
		primary key,
	REF_CONTACT_TYPE_ID NUMBER(14) not null,
	CODE VARCHAR2(1024),
	NAME_KZ VARCHAR2(1024),
	NAME_RU VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RCT_IN_RCTI_77
	on R_REF_CONTACT_TYPE (REF_CONTACT_TYPE_ID, OPEN_DATE)
/

create trigger TRG_R_REF_CONTACT_TYPE_ID
	before insert
	on R_REF_CONTACT_TYPE
	for each row
BEGIN SELECT seq_R_REF_CONTACT_TYPE_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_CONTACT_TYPE_HIS
(
	ID NUMBER(14) not null
		primary key,
	REF_CONTACT_TYPE_ID NUMBER(14) not null,
	CODE VARCHAR2(1024),
	NAME_KZ VARCHAR2(1024),
	NAME_RU VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RCT_IN_RCTI_77_HIS
	on R_REF_CONTACT_TYPE_HIS (REF_CONTACT_TYPE_ID, OPEN_DATE)
/

create trigger TRG_R_REF_CONTACT_TYPE_HIS_ID
	before insert
	on R_REF_CONTACT_TYPE_HIS
	for each row
BEGIN SELECT seq_R_REF_CONTACT_TYPE_HIS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_COUNTRY
(
	ID NUMBER(14) not null
		primary key,
	REF_COUNTRY_ID NUMBER(14) not null,
	CODE VARCHAR2(1024),
	CODE_NUMERIC NUMBER(14),
	NAME_KZ VARCHAR2(1024),
	NAME_RU VARCHAR2(1024),
	SHORT_NAME_KZ VARCHAR2(1024),
	SHORT_NAME_RU VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RC_IN_RCI_33
	on R_REF_COUNTRY (REF_COUNTRY_ID, OPEN_DATE)
/

create trigger TRG_R_REF_COUNTRY_ID
	before insert
	on R_REF_COUNTRY
	for each row
BEGIN SELECT seq_R_REF_COUNTRY_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_COUNTRY_HIS
(
	ID NUMBER(14) not null
		primary key,
	REF_COUNTRY_ID NUMBER(14) not null,
	CODE VARCHAR2(1024),
	CODE_NUMERIC NUMBER(14),
	NAME_KZ VARCHAR2(1024),
	NAME_RU VARCHAR2(1024),
	SHORT_NAME_KZ VARCHAR2(1024),
	SHORT_NAME_RU VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RC_IN_RCI_33_HIS
	on R_REF_COUNTRY_HIS (REF_COUNTRY_ID, OPEN_DATE)
/

create trigger TRG_R_REF_COUNTRY_HIS_ID
	before insert
	on R_REF_COUNTRY_HIS
	for each row
BEGIN SELECT seq_R_REF_COUNTRY_HIS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_CREDITOR_BRANCH
(
	ID NUMBER(14) not null
		primary key,
	REF_CREDITOR_BRANCH_ID NUMBER(14) not null,
	MAIN_OFFICE_ID NUMBER(14),
	REGION_ID NUMBER(14),
	CODE VARCHAR2(1024),
	NAME VARCHAR2(1024),
	SHORT_NAME VARCHAR2(1024),
	MAIN_OFFICE_CODE VARCHAR2(1024),
	REGION_CODE VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RCB_IN_RCBI_0
	on R_REF_CREDITOR_BRANCH (REF_CREDITOR_BRANCH_ID, OPEN_DATE)
/

create trigger TRG_R_REF_CREDITOR_BRANCH_ID
	before insert
	on R_REF_CREDITOR_BRANCH
	for each row
BEGIN SELECT seq_R_REF_CREDITOR_BRANCH_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_CREDITOR_BRANCH_DOC
(
	ID NUMBER(14) not null
		primary key,
	REF_CREDITOR_BRANCH_ID NUMBER(14) not null,
	DOCUMENT_ID NUMBER(14),
	DOC_TYPE_ID NUMBER(14),
	NO VARCHAR2(1024),
	DOC_TYPE_CODE VARCHAR2(1024),
	NAME VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RCBD_IN_RCBI_DI_76
	on R_REF_CREDITOR_BRANCH_DOC (REF_CREDITOR_BRANCH_ID, DOCUMENT_ID, OPEN_DATE)
/

create index RCBD_IN_RCBI_93
	on R_REF_CREDITOR_BRANCH_DOC (REF_CREDITOR_BRANCH_ID, OPEN_DATE)
/

create index RCBD_IN_DI_35
	on R_REF_CREDITOR_BRANCH_DOC (DOCUMENT_ID, OPEN_DATE)
/

create trigger TRG_R_REF_CREDI_BRANCH_DOC_ID
	before insert
	on R_REF_CREDITOR_BRANCH_DOC
	for each row
BEGIN SELECT seq_R_REF_CREDI_BRANCH_DOC_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_CREDITOR_BRANCH_HIS
(
	ID NUMBER(14) not null
		primary key,
	REF_CREDITOR_BRANCH_ID NUMBER(14) not null,
	MAIN_OFFICE_ID NUMBER(14),
	REGION_ID NUMBER(14),
	CODE VARCHAR2(1024),
	NAME VARCHAR2(1024),
	SHORT_NAME VARCHAR2(1024),
	MAIN_OFFICE_CODE VARCHAR2(1024),
	REGION_CODE VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RCB_IN_RCBI_0_HIS
	on R_REF_CREDITOR_BRANCH_HIS (REF_CREDITOR_BRANCH_ID, OPEN_DATE)
/

create trigger TRG_R_REF_CREDI_BRANCH_HIS_ID
	before insert
	on R_REF_CREDITOR_BRANCH_HIS
	for each row
BEGIN SELECT seq_R_REF_CREDI_BRANCH_HIS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_CREDITOR_DOC
(
	ID NUMBER(14) not null
		primary key,
	REF_CREDITOR_ID NUMBER(14) not null,
	DOCUMENT_ID NUMBER(14),
	DOC_TYPE_ID NUMBER(14),
	NO VARCHAR2(1024),
	DOC_TYPE_CODE VARCHAR2(1024),
	NAME VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RCD_IN_RCI_DI_21
	on R_REF_CREDITOR_DOC (REF_CREDITOR_ID, DOCUMENT_ID, OPEN_DATE)
/

create index RCD_IN_RCI_13
	on R_REF_CREDITOR_DOC (REF_CREDITOR_ID, OPEN_DATE)
/

create index RCD_IN_DI_52
	on R_REF_CREDITOR_DOC (DOCUMENT_ID, OPEN_DATE)
/

create trigger TRG_R_REF_CREDITOR_DOC_ID
	before insert
	on R_REF_CREDITOR_DOC
	for each row
BEGIN SELECT seq_R_REF_CREDITOR_DOC_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_CREDITOR_DOC_HIS
(
	ID NUMBER(14) not null
		primary key,
	REF_CREDITOR_ID NUMBER(14) not null,
	DOCUMENT_ID NUMBER(14),
	DOC_TYPE_ID NUMBER(14),
	NO VARCHAR2(1024),
	DOC_TYPE_CODE VARCHAR2(1024),
	NAME VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RCD_IN_RCI_DI_21_HIS
	on R_REF_CREDITOR_DOC_HIS (REF_CREDITOR_ID, DOCUMENT_ID, OPEN_DATE)
/

create index RCD_IN_RCI_13_HIS
	on R_REF_CREDITOR_DOC_HIS (REF_CREDITOR_ID, OPEN_DATE)
/

create index RCD_IN_DI_52_HIS
	on R_REF_CREDITOR_DOC_HIS (DOCUMENT_ID, OPEN_DATE)
/

create trigger TRG_R_REF_CREDITOR_DOC_HIS_ID
	before insert
	on R_REF_CREDITOR_DOC_HIS
	for each row
BEGIN SELECT seq_R_REF_CREDITOR_DOC_HIS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_CREDIT_OBJECT
(
	ID NUMBER(14) not null
		primary key,
	REF_CREDIT_OBJECT_ID NUMBER(14) not null,
	CODE VARCHAR2(1024),
	NAME_KZ VARCHAR2(1024),
	NAME_RU VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RCO_IN_RCOI_86
	on R_REF_CREDIT_OBJECT (REF_CREDIT_OBJECT_ID, OPEN_DATE)
/

create trigger TRG_R_REF_CREDIT_OBJECT_ID
	before insert
	on R_REF_CREDIT_OBJECT
	for each row
BEGIN SELECT seq_R_REF_CREDIT_OBJECT_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_CREDIT_OBJECT_HIS
(
	ID NUMBER(14) not null
		primary key,
	REF_CREDIT_OBJECT_ID NUMBER(14) not null,
	CODE VARCHAR2(1024),
	NAME_KZ VARCHAR2(1024),
	NAME_RU VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RCO_IN_RCOI_86_HIS
	on R_REF_CREDIT_OBJECT_HIS (REF_CREDIT_OBJECT_ID, OPEN_DATE)
/

create trigger TRG_R_REF_CREDIT_OBJECT_HIS_ID
	before insert
	on R_REF_CREDIT_OBJECT_HIS
	for each row
BEGIN SELECT seq_R_REF_CREDIT_OBJECT_HIS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_CREDITOR_BRANCH_DOC_HIS
(
	ID NUMBER(14) not null
		primary key,
	REF_CREDITOR_BRANCH_ID NUMBER(14) not null,
	DOCUMENT_ID NUMBER(14),
	DOC_TYPE_ID NUMBER(14),
	NO VARCHAR2(1024),
	DOC_TYPE_CODE VARCHAR2(1024),
	NAME VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RCBD_IN_RCBI_DI_76_HIS
	on R_REF_CREDITOR_BRANCH_DOC_HIS (REF_CREDITOR_BRANCH_ID, DOCUMENT_ID, OPEN_DATE)
/

create index RCBD_IN_RCBI_93_HIS
	on R_REF_CREDITOR_BRANCH_DOC_HIS (REF_CREDITOR_BRANCH_ID, OPEN_DATE)
/

create index RCBD_IN_DI_35_HIS
	on R_REF_CREDITOR_BRANCH_DOC_HIS (DOCUMENT_ID, OPEN_DATE)
/

create trigger TRG_R_REF_CREDI_NCH_DOC_HIS_ID
	before insert
	on R_REF_CREDITOR_BRANCH_DOC_HIS
	for each row
BEGIN SELECT seq_R_REF_CREDI_NCH_DOC_HIS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_CREDIT_PURPOSE
(
	ID NUMBER(14) not null
		primary key,
	REF_CREDIT_PURPOSE_ID NUMBER(14) not null,
	CODE VARCHAR2(1024),
	NAME_KZ VARCHAR2(1024),
	NAME_RU VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RCP_IN_RCPI_24
	on R_REF_CREDIT_PURPOSE (REF_CREDIT_PURPOSE_ID, OPEN_DATE)
/

create trigger TRG_R_REF_CREDIT_PURPOSE_ID
	before insert
	on R_REF_CREDIT_PURPOSE
	for each row
BEGIN SELECT seq_R_REF_CREDIT_PURPOSE_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_CREDIT_PURPOSE_HIS
(
	ID NUMBER(14) not null
		primary key,
	REF_CREDIT_PURPOSE_ID NUMBER(14) not null,
	CODE VARCHAR2(1024),
	NAME_KZ VARCHAR2(1024),
	NAME_RU VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RCP_IN_RCPI_24_HIS
	on R_REF_CREDIT_PURPOSE_HIS (REF_CREDIT_PURPOSE_ID, OPEN_DATE)
/

create trigger TRG_R_REF_CREDI_PURPOSE_HIS_ID
	before insert
	on R_REF_CREDIT_PURPOSE_HIS
	for each row
BEGIN SELECT seq_R_REF_CREDI_PURPOSE_HIS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_CREDIT_TYPE
(
	ID NUMBER(14) not null
		primary key,
	REF_CREDIT_TYPE_ID NUMBER(14) not null,
	CODE VARCHAR2(1024),
	KIND_ID NUMBER(14),
	NAME_KZ VARCHAR2(1024),
	NAME_RU VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RCT_IN_RCTI_32
	on R_REF_CREDIT_TYPE (REF_CREDIT_TYPE_ID, OPEN_DATE)
/

create trigger TRG_R_REF_CREDIT_TYPE_ID
	before insert
	on R_REF_CREDIT_TYPE
	for each row
BEGIN SELECT seq_R_REF_CREDIT_TYPE_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_CREDIT_TYPE_HIS
(
	ID NUMBER(14) not null
		primary key,
	REF_CREDIT_TYPE_ID NUMBER(14) not null,
	CODE VARCHAR2(1024),
	KIND_ID NUMBER(14),
	NAME_KZ VARCHAR2(1024),
	NAME_RU VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RCT_IN_RCTI_32_HIS
	on R_REF_CREDIT_TYPE_HIS (REF_CREDIT_TYPE_ID, OPEN_DATE)
/

create trigger TRG_R_REF_CREDIT_TYPE_HIS_ID
	before insert
	on R_REF_CREDIT_TYPE_HIS
	for each row
BEGIN SELECT seq_R_REF_CREDIT_TYPE_HIS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_CURRENCY
(
	ID NUMBER(14) not null
		primary key,
	REF_CURRENCY_ID NUMBER(14) not null,
	CODE VARCHAR2(1024),
	IS_CONVERTIBLE NUMBER(1),
	NAME_KZ VARCHAR2(1024),
	NAME_RU VARCHAR2(1024),
	RATING VARCHAR2(1024),
	SHORT_NAME VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RC_IN_RCI_64
	on R_REF_CURRENCY (REF_CURRENCY_ID, OPEN_DATE)
/

create trigger TRG_R_REF_CURRENCY_ID
	before insert
	on R_REF_CURRENCY
	for each row
BEGIN SELECT seq_R_REF_CURRENCY_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_CURRENCY_HIS
(
	ID NUMBER(14) not null
		primary key,
	REF_CURRENCY_ID NUMBER(14) not null,
	CODE VARCHAR2(1024),
	IS_CONVERTIBLE NUMBER(1),
	NAME_KZ VARCHAR2(1024),
	NAME_RU VARCHAR2(1024),
	RATING VARCHAR2(1024),
	SHORT_NAME VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RC_IN_RCI_64_HIS
	on R_REF_CURRENCY_HIS (REF_CURRENCY_ID, OPEN_DATE)
/

create trigger TRG_R_REF_CURRENCY_HIS_ID
	before insert
	on R_REF_CURRENCY_HIS
	for each row
BEGIN SELECT seq_R_REF_CURRENCY_HIS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_DEBTOR_TYPE
(
	ID NUMBER(14) not null
		primary key,
	REF_DEBTOR_TYPE_ID NUMBER(14) not null,
	CODE VARCHAR2(1024),
	NAME_KZ VARCHAR2(1024),
	NAME_RU VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RDT_IN_RDTI_43
	on R_REF_DEBTOR_TYPE (REF_DEBTOR_TYPE_ID, OPEN_DATE)
/

create trigger TRG_R_REF_DEBTOR_TYPE_ID
	before insert
	on R_REF_DEBTOR_TYPE
	for each row
BEGIN SELECT seq_R_REF_DEBTOR_TYPE_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_DEBTOR_TYPE_HIS
(
	ID NUMBER(14) not null
		primary key,
	REF_DEBTOR_TYPE_ID NUMBER(14) not null,
	CODE VARCHAR2(1024),
	NAME_KZ VARCHAR2(1024),
	NAME_RU VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RDT_IN_RDTI_43_HIS
	on R_REF_DEBTOR_TYPE_HIS (REF_DEBTOR_TYPE_ID, OPEN_DATE)
/

create trigger TRG_R_REF_DEBTOR_TYPE_HIS_ID
	before insert
	on R_REF_DEBTOR_TYPE_HIS
	for each row
BEGIN SELECT seq_R_REF_DEBTOR_TYPE_HIS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_DOC_TYPE
(
	ID NUMBER(14) not null
		primary key,
	REF_DOC_TYPE_ID NUMBER(14) not null,
	CODE VARCHAR2(1024),
	IS_IDENTIFICATION NUMBER(1),
	IS_ORGANIZATION_DOC NUMBER(1),
	IS_PERSON_DOC NUMBER(1),
	NAME_KZ VARCHAR2(1024),
	NAME_RU VARCHAR2(1024),
	SHORT_NAME_KZ VARCHAR2(1024),
	SHORT_NAME_RU VARCHAR2(1024),
	SIGN_COUNT NUMBER(14),
	WEIGHT NUMBER(14),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RDT_IN_RDTI_11
	on R_REF_DOC_TYPE (REF_DOC_TYPE_ID, OPEN_DATE)
/

create trigger TRG_R_REF_DOC_TYPE_ID
	before insert
	on R_REF_DOC_TYPE
	for each row
BEGIN SELECT seq_R_REF_DOC_TYPE_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_DOC_TYPE_HIS
(
	ID NUMBER(14) not null
		primary key,
	REF_DOC_TYPE_ID NUMBER(14) not null,
	CODE VARCHAR2(1024),
	IS_IDENTIFICATION NUMBER(1),
	IS_ORGANIZATION_DOC NUMBER(1),
	IS_PERSON_DOC NUMBER(1),
	NAME_KZ VARCHAR2(1024),
	NAME_RU VARCHAR2(1024),
	SHORT_NAME_KZ VARCHAR2(1024),
	SHORT_NAME_RU VARCHAR2(1024),
	SIGN_COUNT NUMBER(14),
	WEIGHT NUMBER(14),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RDT_IN_RDTI_11_HIS
	on R_REF_DOC_TYPE_HIS (REF_DOC_TYPE_ID, OPEN_DATE)
/

create trigger TRG_R_REF_DOC_TYPE_HIS_ID
	before insert
	on R_REF_DOC_TYPE_HIS
	for each row
BEGIN SELECT seq_R_REF_DOC_TYPE_HIS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_ECON_TRADE
(
	ID NUMBER(14) not null
		primary key,
	REF_ECON_TRADE_ID NUMBER(14) not null,
	CODE VARCHAR2(1024),
	NAME_KZ VARCHAR2(1024),
	NAME_RU VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RET_IN_RETI_79
	on R_REF_ECON_TRADE (REF_ECON_TRADE_ID, OPEN_DATE)
/

create trigger TRG_R_REF_ECON_TRADE_ID
	before insert
	on R_REF_ECON_TRADE
	for each row
BEGIN SELECT seq_R_REF_ECON_TRADE_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_ECON_TRADE_HIS
(
	ID NUMBER(14) not null
		primary key,
	REF_ECON_TRADE_ID NUMBER(14) not null,
	CODE VARCHAR2(1024),
	NAME_KZ VARCHAR2(1024),
	NAME_RU VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RET_IN_RETI_79_HIS
	on R_REF_ECON_TRADE_HIS (REF_ECON_TRADE_ID, OPEN_DATE)
/

create trigger TRG_R_REF_ECON_TRADE_HIS_ID
	before insert
	on R_REF_ECON_TRADE_HIS
	for each row
BEGIN SELECT seq_R_REF_ECON_TRADE_HIS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_ENTERPRISE_TYPE
(
	ID NUMBER(14) not null
		primary key,
	REF_ENTERPRISE_TYPE_ID NUMBER(14) not null,
	CODE VARCHAR2(1024),
	IS_ORGANIZATION NUMBER(1),
	IS_SE NUMBER(1),
	NAME_KZ VARCHAR2(1024),
	NAME_RU VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RET_IN_RETI_0
	on R_REF_ENTERPRISE_TYPE (REF_ENTERPRISE_TYPE_ID, OPEN_DATE)
/

create trigger TRG_R_REF_ENTERPRISE_TYPE_ID
	before insert
	on R_REF_ENTERPRISE_TYPE
	for each row
BEGIN SELECT seq_R_REF_ENTERPRISE_TYPE_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_ENTERPRISE_TYPE_HIS
(
	ID NUMBER(14) not null
		primary key,
	REF_ENTERPRISE_TYPE_ID NUMBER(14) not null,
	CODE VARCHAR2(1024),
	IS_ORGANIZATION NUMBER(1),
	IS_SE NUMBER(1),
	NAME_KZ VARCHAR2(1024),
	NAME_RU VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RET_IN_RETI_0_HIS
	on R_REF_ENTERPRISE_TYPE_HIS (REF_ENTERPRISE_TYPE_ID, OPEN_DATE)
/

create trigger TRG_R_REF_ENTER_SE_TYPE_HIS_ID
	before insert
	on R_REF_ENTERPRISE_TYPE_HIS
	for each row
BEGIN SELECT seq_R_REF_ENTER_SE_TYPE_HIS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_FINANCE_SOURCE
(
	ID NUMBER(14) not null
		primary key,
	REF_FINANCE_SOURCE_ID NUMBER(14) not null,
	CODE VARCHAR2(1024),
	NAME_KZ VARCHAR2(1024),
	NAME_RU VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RFS_IN_RFSI_24
	on R_REF_FINANCE_SOURCE (REF_FINANCE_SOURCE_ID, OPEN_DATE)
/

create trigger TRG_R_REF_FINANCE_SOURCE_ID
	before insert
	on R_REF_FINANCE_SOURCE
	for each row
BEGIN SELECT seq_R_REF_FINANCE_SOURCE_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_FINANCE_SOURCE_HIS
(
	ID NUMBER(14) not null
		primary key,
	REF_FINANCE_SOURCE_ID NUMBER(14) not null,
	CODE VARCHAR2(1024),
	NAME_KZ VARCHAR2(1024),
	NAME_RU VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RFS_IN_RFSI_24_HIS
	on R_REF_FINANCE_SOURCE_HIS (REF_FINANCE_SOURCE_ID, OPEN_DATE)
/

create trigger TRG_R_REF_FINAN_SOURCE_HIS_ID
	before insert
	on R_REF_FINANCE_SOURCE_HIS
	for each row
BEGIN SELECT seq_R_REF_FINAN_SOURCE_HIS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_LEGAL_FORM
(
	ID NUMBER(14) not null
		primary key,
	REF_LEGAL_FORM_ID NUMBER(14) not null,
	CODE VARCHAR2(1024),
	NAME_KZ VARCHAR2(1024),
	NAME_RU VARCHAR2(1024),
	SHORT_NAME_KZ VARCHAR2(1024),
	SHORT_NAME_RU VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RLF_IN_RLFI_89
	on R_REF_LEGAL_FORM (REF_LEGAL_FORM_ID, OPEN_DATE)
/

create trigger TRG_R_REF_LEGAL_FORM_ID
	before insert
	on R_REF_LEGAL_FORM
	for each row
BEGIN SELECT seq_R_REF_LEGAL_FORM_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_LEGAL_FORM_HIS
(
	ID NUMBER(14) not null
		primary key,
	REF_LEGAL_FORM_ID NUMBER(14) not null,
	CODE VARCHAR2(1024),
	NAME_KZ VARCHAR2(1024),
	NAME_RU VARCHAR2(1024),
	SHORT_NAME_KZ VARCHAR2(1024),
	SHORT_NAME_RU VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RLF_IN_RLFI_89_HIS
	on R_REF_LEGAL_FORM_HIS (REF_LEGAL_FORM_ID, OPEN_DATE)
/

create trigger TRG_R_REF_LEGAL_FORM_HIS_ID
	before insert
	on R_REF_LEGAL_FORM_HIS
	for each row
BEGIN SELECT seq_R_REF_LEGAL_FORM_HIS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_OFFSHORE
(
	ID NUMBER(14) not null
		primary key,
	REF_OFFSHORE_ID NUMBER(14) not null,
	COUNTRY_ID NUMBER(14),
	CODE VARCHAR2(1024),
	NAME_KZ VARCHAR2(1024),
	NAME_RU VARCHAR2(1024),
	COUNTRY_CODE VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RO_IN_ROI_95
	on R_REF_OFFSHORE (REF_OFFSHORE_ID, OPEN_DATE)
/

create trigger TRG_R_REF_OFFSHORE_ID
	before insert
	on R_REF_OFFSHORE
	for each row
BEGIN SELECT seq_R_REF_OFFSHORE_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_OFFSHORE_HIS
(
	ID NUMBER(14) not null
		primary key,
	REF_OFFSHORE_ID NUMBER(14) not null,
	COUNTRY_ID NUMBER(14),
	CODE VARCHAR2(1024),
	NAME_KZ VARCHAR2(1024),
	NAME_RU VARCHAR2(1024),
	COUNTRY_CODE VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RO_IN_ROI_95_HIS
	on R_REF_OFFSHORE_HIS (REF_OFFSHORE_ID, OPEN_DATE)
/

create trigger TRG_R_REF_OFFSHORE_HIS_ID
	before insert
	on R_REF_OFFSHORE_HIS
	for each row
BEGIN SELECT seq_R_REF_OFFSHORE_HIS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_PLEDGE_TYPE
(
	ID NUMBER(14) not null
		primary key,
	REF_PLEDGE_TYPE_ID NUMBER(14) not null,
	CODE VARCHAR2(1024),
	IS_LIQUID_ALL NUMBER(1),
	IS_LIQUID_INVEST NUMBER(1),
	NAME_KZ VARCHAR2(1024),
	NAME_RU VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RPT_IN_RPTI_2
	on R_REF_PLEDGE_TYPE (REF_PLEDGE_TYPE_ID, OPEN_DATE)
/

create trigger TRG_R_REF_PLEDGE_TYPE_ID
	before insert
	on R_REF_PLEDGE_TYPE
	for each row
BEGIN SELECT seq_R_REF_PLEDGE_TYPE_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_PLEDGE_TYPE_HIS
(
	ID NUMBER(14) not null
		primary key,
	REF_PLEDGE_TYPE_ID NUMBER(14) not null,
	CODE VARCHAR2(1024),
	IS_LIQUID_ALL NUMBER(1),
	IS_LIQUID_INVEST NUMBER(1),
	NAME_KZ VARCHAR2(1024),
	NAME_RU VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RPT_IN_RPTI_2_HIS
	on R_REF_PLEDGE_TYPE_HIS (REF_PLEDGE_TYPE_ID, OPEN_DATE)
/

create trigger TRG_R_REF_PLEDGE_TYPE_HIS_ID
	before insert
	on R_REF_PLEDGE_TYPE_HIS
	for each row
BEGIN SELECT seq_R_REF_PLEDGE_TYPE_HIS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_PORTFOLIO
(
	ID NUMBER(14) not null
		primary key,
	REF_PORTFOLIO_ID NUMBER(14) not null,
	CREDITOR_ID NUMBER(14),
	CODE VARCHAR2(1024),
	NAME_KZ VARCHAR2(1024),
	NAME_RU VARCHAR2(1024),
	CREDITOR_CODE VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RP_IN_RPI_72
	on R_REF_PORTFOLIO (REF_PORTFOLIO_ID, OPEN_DATE)
/

create trigger TRG_R_REF_PORTFOLIO_ID
	before insert
	on R_REF_PORTFOLIO
	for each row
BEGIN SELECT seq_R_REF_PORTFOLIO_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_PORTFOLIO_HIS
(
	ID NUMBER(14) not null
		primary key,
	REF_PORTFOLIO_ID NUMBER(14) not null,
	CREDITOR_ID NUMBER(14),
	CODE VARCHAR2(1024),
	NAME_KZ VARCHAR2(1024),
	NAME_RU VARCHAR2(1024),
	CREDITOR_CODE VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RP_IN_RPI_72_HIS
	on R_REF_PORTFOLIO_HIS (REF_PORTFOLIO_ID, OPEN_DATE)
/

create trigger TRG_R_REF_PORTFOLIO_HIS_ID
	before insert
	on R_REF_PORTFOLIO_HIS
	for each row
BEGIN SELECT seq_R_REF_PORTFOLIO_HIS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_REGION
(
	ID NUMBER(14) not null
		primary key,
	REF_REGION_ID NUMBER(14) not null,
	CODE VARCHAR2(1024),
	NAME_KZ VARCHAR2(1024),
	NAME_RU VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RR_IN_RRI_76
	on R_REF_REGION (REF_REGION_ID, OPEN_DATE)
/

create trigger TRG_R_REF_REGION_ID
	before insert
	on R_REF_REGION
	for each row
BEGIN SELECT seq_R_REF_REGION_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_REGION_HIS
(
	ID NUMBER(14) not null
		primary key,
	REF_REGION_ID NUMBER(14) not null,
	CODE VARCHAR2(1024),
	NAME_KZ VARCHAR2(1024),
	NAME_RU VARCHAR2(1024),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RR_IN_RRI_76_HIS
	on R_REF_REGION_HIS (REF_REGION_ID, OPEN_DATE)
/

create trigger TRG_R_REF_REGION_HIS_ID
	before insert
	on R_REF_REGION_HIS
	for each row
BEGIN SELECT seq_R_REF_REGION_HIS_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_SUBJECT_TYPE
(
	ID NUMBER(14) not null
		primary key,
	REF_SUBJECT_TYPE_ID NUMBER(14) not null,
	CODE VARCHAR2(1024),
	KIND_ID NUMBER(14),
	NAME_KZ VARCHAR2(1024),
	NAME_RU VARCHAR2(1024),
	REPORT_PERIOD_DURATION_MONTHS NUMBER(14),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RST_IN_RSTI_49
	on R_REF_SUBJECT_TYPE (REF_SUBJECT_TYPE_ID, OPEN_DATE)
/

create trigger TRG_R_REF_SUBJECT_TYPE_ID
	before insert
	on R_REF_SUBJECT_TYPE
	for each row
BEGIN SELECT seq_R_REF_SUBJECT_TYPE_ID.nextval INTO :new.ID FROM dual; END;
/

create table R_REF_SUBJECT_TYPE_HIS
(
	ID NUMBER(14) not null
		primary key,
	REF_SUBJECT_TYPE_ID NUMBER(14) not null,
	CODE VARCHAR2(1024),
	KIND_ID NUMBER(14),
	NAME_KZ VARCHAR2(1024),
	NAME_RU VARCHAR2(1024),
	REPORT_PERIOD_DURATION_MONTHS NUMBER(14),
	CDC DATE,
	OPEN_DATE DATE,
	CLOSE_DATE DATE
)
/

create index RST_IN_RSTI_49_HIS
	on R_REF_SUBJECT_TYPE_HIS (REF_SUBJECT_TYPE_ID, OPEN_DATE)
/

create trigger TRG_R_REF_SUBJECT_TYPE_HIS_ID
	before insert
	on R_REF_SUBJECT_TYPE_HIS
	for each row
BEGIN SELECT seq_R_REF_SUBJECT_TYPE_HIS_ID.nextval INTO :new.ID FROM dual; END;
/

