/*  */

CREATE USER C##SHOWCASE IDENTIFIED BY SHOWCASE
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
PROFILE DEFAULT;


GRANT CONNECT TO C##SHOWCASE;
GRANT RESOURCE TO C##SHOWCASE;
GRANT CREATE ANY INDEX TO C##SHOWCASE;
GRANT CREATE ANY TABLE TO C##SHOWCASE;
GRANT CREATE TABLE TO C##SHOWCASE;
GRANT CREATE USER TO C##SHOWCASE;
GRANT CREATE VIEW TO C##SHOWCASE;
GRANT EXECUTE ANY PROCEDURE TO C##SHOWCASE;
GRANT UNLIMITED TABLESPACE TO C##SHOWCASE;



