package com.bsbnb.creditregistry.portlets.report;

/**
 *
 * @author Aidar.Myrzahanov
 */
public enum Localization {
    DOWNLOAD_XLS_BUTTON_CAPTION("DOWNLOAD-XLS-BUTTON-CAPTION"),
    DOWNLOAD_FILE_BUTTON_CAPTION("DOWNLOAD-FILE-BUTTON-CAPTION"),
    REPORT_BUILD_STARTED("REPORT-BUILD-STARTED"),
    REPORT_BUILD_FINISHED("REPORT-BUILD-FINISHED"),
    LOAD_RECORDS_FROM_TO("LOAD-RECORDS-FROM-TO"),
    LOAD_RESULTS("LOAD-RESULTS"),
    EXPORT_FAILED("EXPORT-FAILED-WITH-REASON"),
    START_HEADER("START-HEADER"),
    REPORTS_TABLE_CAPTION("REPORTS-TABLE-CAPTION"),
    SHOW_REPORTS_LIST_BUTTON_CAPTION("SHOW-REPORTS-LIST-BUTTON-CAPTION"),
    SELECTED_REPORT_HEADER("SELECTED-REPORT-HEADER"),
    NO_RECORDS("NO-RECORDS"),
    NOT_APPROVED("NOT-APPROVED"),
    REPORT_LIST_TAB_PAGE_CAPTION("REPORT-LIST-TAB-PAGE-CAPTION"),
    GENERATED_REPORTS_TAB_PAGE_CAPTION("GENERATED-REPORTS-TAB-PAGE-CAPTION"),
    LOADS_TABLE_CAPTION("LOADS-TABLE-CAPTION"),
    FILES_TABLE_CAPTION("FILES-TABLE-CAPTION"), 
    REFRESH_TABLE_DESCRIPTION("REFRESH-TABLE-DESCRIPTION"), 
    FILE_DOES_NOT_EXIST_MESSAGE("FILE-DOES-NOT-EXIST-MESSAGE");
    private String key;
    private Localization(String key) {
        this.key = key;
    }
    
    public String getValue() {
        return ReportApplication.getResourceString(key);
    }
}
