package com.bsbnb.creditregistry.portlets.approval.ui;

/**
 *
 * @author Aidar.Myrzahanov
 */
public enum Localization {
    MESSAGE_USER_HAS_NO_ACCESS_TO_CREDITORS("MESSAGE-USER-HAS-NO-ACCESS-TO-CREDITORS"),
    MESSAGE_USER_HAS_ACCESS_TO_MULTIPLE_CREDITORS("MESSAGE-USER-HAS-ACCESS-TO-MULTIPLE-CREDITORS"),
    MESSAGE_ONLY_BANK_AND_NB_USERS_CAN_ACCESS_APP("MESSAGE_ONLY_BANK_AND_NB_USERS_CAN_ACCESS_APP"), 
    ERROR_MESSAGE_HEADER("ERROR-MESSAGE-HEADER"),
    REPORT_DATE_CAPTION("REPORT-DATE-CAPTION"),
    SHOW_CREDITORS_CAPTION("SHOW-CREDITORS-CAPTION"),
    CREDITORS_TABLE_COLUMN_NAMES("CREDITORS-TABLE-COLUMN-NAMES"),
    CREDITORS_TABLE_COLUMN_CAPTIONS("CREDITORS-TABLE-COLUMN-CAPTIONS"),
    RETURN_TO_LIST_BUTTON_CAPTION("RETURN-TO-LIST-BUTTON-CAPTION"),
    EXPORT_TABLE_COLUMN_NAMES("EXPORT-TABLE-COLUMN-NAMES"),
    EXPORT_TABLE_COLUMN_CAPTIONS("EXPORT-TABLE-COLUMN-CAPTIONS"), 
    REPORT_HEADER("REPORT-HEADER"),
    REPORT_DATE_HEADER("REPORT-DATE-HEADER"), 
    EXPORT_TO_XLS_BUTTON_CAPTION("EXPORT_TO_XLS_BUTTON_CAPTION"),
    REPORT_STATUS_LABEL_CAPTION("REPORT-STATUS-LABEL-CAPTION"),
    CONTRACTS_COUNT_LABEL_CAPTION("CONTRACTS-COUNT-LABEL-CAPTION"),
    CROSS_CHECK_RESULT_LABEL_CAPTION("CROSS-CHECK-RESULT-LABEL-CAPTION"),
    CROSS_CHECK_DID_NOT_RUN("CROSS-CHECK-DID-NOT-RUN"),
    APPROVE_REPORT_BUTTON_CAPTION("APPROVE-REPORT-BUTTON-CAPTION"), 
    NEW_MESSAGE_CAPTION("NEW-MESSAGE-CAPTION"), 
    ADD_NEW_MESSAGE_BUTTON_CAPTION("ADD-NEW-MESSAGE-BUTTON-CAPTION"),
    REPORT_APPROVE_MESSAGE_TEMPLATE("REPORT-APPROVE-MESSAGE-TEMPLATE"), 
    UNDO_APPROVE_REPORT_BUTTON_CAPTION("UNDO-APPROVE-REPORT-BUTTON-CAPTION"), 
    UPLOAD_BUTTON_CAPTION("UPLOAD-BUTTON-CAPTION"), 
    ADD_ATTACHMENT_BUTTON_CAPTION("ADD-ATTACHMENT-BUTTON-CAPTION"), 
    FILE_EXCEEDED_FILE_LIMIT_OF_5_MB("FILE_EXCEEDED_FILE_LIMIT_OF_5_MB"), 
    NO_REPORTS_MESSAGE("NO-REPORTS-MESSAGE"),
    UPDATE_LAST_MANUAL_EDIT_DATE("UPDATE-LAST-MANUAL-EDIT-DATE"),
    LAST_MANUAL_EDIT_CAPTION("LAST-MANUAL-EDIT-CAPTION"),
    EMPTY_DATE_STRING("EMPTY-DATE-STRING");
    
    private final String key;
    private Localization(String key) {
        this.key = key;
    }
    
    public String getKey() {
        return key;
    }
}
