package com.bsbnb.usci.portlets.protocol.ui;

import com.bsbnb.usci.portlets.protocol.PortletEnvironmentFacade;

/**
 *
 * @author Aidar.Myrzahanov
 */
public enum Localization {
    MESSAGE_NO_CREDITORS("MESSAGE.NO-CREDITORS"),
    MESSAGE_NO_DATA("MESSAGE.NO-DATA"),
    MESSAGE_CREDITOR_NOT_SELECTED("MESSAGE.CREDITOR-NOT-SELECTED"),
    MESSAGE_EXPORT_FAILED("MESSAGE.EXPORT-FAILED"),
    FILES_TABLE_CAPTION("FILES-TABLE-CAPTION"),
    CROSS_CHECK_MISMATCH_NOTE("CROSS-CHECK-MISMATCH-NOTE"),
    CREDITORS_COMBOBOX_CAPTION("CREDITORS-COMBOBOX-CAPTION"),
    SELECT_ALL_CREDITORS_CHECKBOX_CAPTION("SELECT-ALL-CREDITORS-CHECKBOX-CAPTION"),
    SHOW_BUTTON_CAPTION("SHOW-BUTTON-CAPTION"),
    PROTOCOL_TABLE_CAPTION("PROTOCOL-TABLE-CAPTION"),
    EXPORT_TO_XLS_CAPTION("EXPORT-TO-XLS-BUTTON-CAPTION"),
    INPUT_INFO_LEVEL_PROTOCOL_MESSAGE("INPUT-INFO-LEVEL-PROTOCOL-MESSAGE"),
    CONTRACT_NO_CAPTION("CONTRACT-NO-CAPTION"),
    GROUP_PROTOCOL_RECORDS_BUTTON_CAPTION("GROUP-PROTOCOL-RECORDS-BUTTON-CAPTION"),
    UNGROUP_PROTOCOL_RECORDS_BUTTON_CAPTION("UNGROUP-PROTOCOL-RECORDS-BUTTON-CAPTION"),
    NO_PROTOCOLS_BY_INPUT_INFO_MESSAGE("NO-PROTOCOLS-BY-INPUT-INFO-MESSAGE"), 
    EXPORT_NUMBERS("EXPORT-NUMBERS"), 
    EXPORT_TO_XML("EXPORT-TO-XML"),
    INFORMATION_MESSAGES("INFORMATION-MESSAGES"), 
    REPORT_DATE_CAPTION("REPORT-DATE-CAPTION"),
    SIGNATURE_CAPTION("SIGNATURE-CAPTION"),
    NO_SIGNATURE_CAPTION("NO-SIGNATURE-CAPTION");

    private String key;
    private Localization(String key) {
        this.key = key;
    }
    
    public String getValue() {
        return PortletEnvironmentFacade.get().getResourceString(key);
    }
    
    public String getKey() {
        return key;
    }
}
