ALTER TABLE EAV_M_COMPLEX_SET ADD HISTORY_TYPE NUMBER(2);
ALTER TABLE EAV_M_COMPLEX_ATTRIBUTES ADD HISTORY_TYPE NUMBER(2);
ALTER TABLE EAV_M_SIMPLE_SET ADD HISTORY_TYPE NUMBER(2);
ALTER TABLE EAV_M_SIMPLE_ATTRIBUTES ADD HISTORY_TYPE NUMBER(2);

