  CREATE TABLE "CORE"."LX_ACTUAL_ISSUE_DATE_MISM"
   (	"CREDIT_ID" NUMBER(14,0),
	"P_CONT_NO" VARCHAR2(45),
	"P_CONT_DATE" DATE,
	"A_ISSUE_DATE" DATE,
	"CREDITOR_ID" NUMBER,
	"CR_P_CONT_DATE" DATE,
	"CR_ISSUE_DATE" DATE,
	"CR_NOT_FOUND" NUMBER(1,0) DEFAULT 0,
	"P_CONT_ID" NUMBER
   )

CREATE TABLE "CORE"."LX_CONT_MATURITY_DATE_MISM"
   (	"CREDIT_ID" NUMBER(14,0),
	"P_CONT_NO" VARCHAR2(45),
	"P_CONT_DATE" DATE,
	"CONT_MATURITY_DATE" DATE,
	"CREDITOR_ID" NUMBER,
	"CR_P_CONT_DATE" DATE,
	"CR_ISSUE_DATE" DATE,
	"CR_NOT_FOUND" NUMBER(1,0) DEFAULT 0,
	"P_CONT_ID" NUMBER
   )

CREATE TABLE "CORE"."LX_DEBT_PASTDUE_CD_RD"
   (	"PASTDUE_ID" NUMBER(14,0),
	"DEPT_ID" NUMBER(14,0),
	"REMAINS_ID" NUMBER(14,0),
	"CHANGE_ID" NUMBER(14,0),
	"CREDIT_ID" NUMBER(14,0),
	"P_CONT_NO" VARCHAR2(45),
	"P_CONT_DATE" DATE,
	"REPORT_DATE" DATE,
	"CLOSE_DATE" DATE,
	"CR_CLOSE_DATE" DATE,
	"CR_REPORT_DATE" DATE,
	"CR_NOT_FOUND" NUMBER(1,0) DEFAULT 0,
	"CREDITOR_ID" NUMBER
   )

   CREATE TABLE "CORE"."LX_DEBT_PASTDUE_OD_VS_CD"
   (	"PASTDUE_ID" NUMBER(14,0),
	"DEPT_ID" NUMBER(14,0),
	"REMAINS_ID" NUMBER(14,0),
	"CHANGE_ID" NUMBER(14,0),
	"CREDIT_ID" NUMBER(14,0),
	"P_CONT_NO" VARCHAR2(45),
	"P_CONT_DATE" DATE,
	"REPORT_DATE" DATE,
	"OPEN_DATE" DATE,
	"CLOSE_DATE" DATE,
	"CR_OPEN_DATE" DATE,
	"CR_CLOSE_DATE" DATE,
	"CR_NOT_FOUND" NUMBER(1,0) DEFAULT 0,
	"CREDITOR_ID" NUMBER
   )

   CREATE TABLE "CORE"."LX_DEBT_PASTDUE_VAL1"
   (	"PASTDUE_ID" NUMBER(14,0),
	"DEPT_ID" NUMBER(14,0),
	"REMAINS_ID" NUMBER(14,0),
	"CHANGE_ID" NUMBER(14,0),
	"CREDIT_ID" NUMBER(14,0),
	"P_CONT_NO" VARCHAR2(45),
	"P_CONT_DATE" DATE,
	"REPORT_DATE" DATE,
	"VALUE" NUMBER(17,3),
	"OPEN_DATE" DATE,
	"CLOSE_DATE" DATE,
	"CR_VALUE" NUMBER(17,3),
	"CR_OPEN_DATE" DATE,
	"CR_CLOSE_DATE" DATE,
	"CR_NOT_FOUND" NUMBER(1,0) DEFAULT 0,
	"CREDITOR_ID" NUMBER
   )

   CREATE TABLE "CORE"."LX_DEBT_PASTDUE_VAL2"
   (	"PASTDUE_ID" NUMBER(14,0),
	"DEPT_ID" NUMBER(14,0),
	"REMAINS_ID" NUMBER(14,0),
	"CHANGE_ID" NUMBER(14,0),
	"CREDIT_ID" NUMBER(14,0),
	"P_CONT_NO" VARCHAR2(45),
	"P_CONT_DATE" DATE,
	"REPORT_DATE" DATE,
	"VALUE" NUMBER(17,3),
	"OPEN_DATE" DATE,
	"CR_VALUE" NUMBER(17,3),
	"CR_OPEN_DATE" DATE,
	"CR_NOT_FOUND" NUMBER(1,0) DEFAULT 0,
	"CREDITOR_ID" NUMBER
   )

   CREATE TABLE "CORE"."LX_DEBT_PASTDUE_VS_RD"
   (	"PASTDUE_ID" NUMBER(14,0),
	"DEPT_ID" NUMBER(14,0),
	"REMAINS_ID" NUMBER(14,0),
	"CHANGE_ID" NUMBER(14,0),
	"CREDIT_ID" NUMBER(14,0),
	"P_CONT_NO" VARCHAR2(45),
	"P_CONT_DATE" DATE,
	"REPORT_DATE" DATE,
	"OPEN_DATE" DATE,
	"CR_REPORT_DATE" DATE,
	"CR_OPEN_DATE" DATE,
	"CR_NOT_FOUND" NUMBER(1,0) DEFAULT 0,
	"CR_CREDIT_ID" NUMBER,
	"CREDITOR_ID" NUMBER
   )

   CREATE TABLE "CORE"."LX_INTER_PASTDUE_CD_RD"
   (	"PASTDUE_ID" NUMBER(14,0),
	"INTEREST_ID" NUMBER(14,0),
	"REMAINS_ID" NUMBER(14,0),
	"CHANGE_ID" NUMBER(14,0),
	"CREDIT_ID" NUMBER(14,0),
	"P_CONT_NO" VARCHAR2(45),
	"P_CONT_DATE" DATE,
	"REPORT_DATE" DATE,
	"CLOSE_DATE" DATE,
	"CR_CLOSE_DATE" DATE,
	"CR_REPORT_DATE" DATE,
	"CR_NOT_FOUND" NUMBER(1,0) DEFAULT 0,
	"CREDITOR_ID" NUMBER
   )

   CREATE TABLE "CORE"."LX_INTER_PASTDUE_OD_VS_CD"
   (	"PASTDUE_ID" NUMBER(14,0),
	"INTEREST_ID" NUMBER(14,0),
	"REMAINS_ID" NUMBER(14,0),
	"CHANGE_ID" NUMBER(14,0),
	"CREDIT_ID" NUMBER(14,0),
	"P_CONT_NO" VARCHAR2(45),
	"P_CONT_DATE" DATE,
	"REPORT_DATE" DATE,
	"OPEN_DATE" DATE,
	"CLOSE_DATE" DATE,
	"CR_OPEN_DATE" DATE,
	"CR_CLOSE_DATE" DATE,
	"CR_NOT_FOUND" NUMBER(1,0) DEFAULT 0,
	"CREDITOR_ID" NUMBER
   )

   CREATE TABLE "CORE"."LX_INTER_PASTDUE_VAL1"
   (	"PASTDUE_ID" NUMBER(14,0),
	"INTEREST_ID" NUMBER(14,0),
	"REMAINS_ID" NUMBER(14,0),
	"CHANGE_ID" NUMBER(14,0),
	"CREDIT_ID" NUMBER(14,0),
	"P_CONT_NO" VARCHAR2(45),
	"P_CONT_DATE" DATE,
	"REPORT_DATE" DATE,
	"VALUE" NUMBER(17,3),
	"OPEN_DATE" DATE,
	"CLOSE_DATE" DATE,
	"CR_VALUE" NUMBER(17,3),
	"CR_OPEN_DATE" DATE,
	"CR_CLOSE_DATE" DATE,
	"CR_NOT_FOUND" NUMBER(1,0) DEFAULT 0,
	"CREDITOR_ID" NUMBER
   )

   CREATE TABLE "CORE"."LX_INTER_PASTDUE_VAL2"
   (	"PASTDUE_ID" NUMBER(14,0),
	"INTEREST_ID" NUMBER(14,0),
	"REMAINS_ID" NUMBER(14,0),
	"CHANGE_ID" NUMBER(14,0),
	"CREDIT_ID" NUMBER(14,0),
	"P_CONT_NO" VARCHAR2(45),
	"P_CONT_DATE" DATE,
	"REPORT_DATE" DATE,
	"VALUE" NUMBER(17,3),
	"OPEN_DATE" DATE,
	"CR_VALUE" NUMBER(17,3),
	"CR_OPEN_DATE" DATE,
	"CR_NOT_FOUND" NUMBER(1,0) DEFAULT 0,
	"CREDITOR_ID" NUMBER
   )

    CREATE TABLE "CORE"."LX_INTER_PASTDUE_VS_RD"
   (	"PASTDUE_ID" NUMBER(14,0),
	"INTEREST_ID" NUMBER(14,0),
	"REMAINS_ID" NUMBER(14,0),
	"CHANGE_ID" NUMBER(14,0),
	"CREDIT_ID" NUMBER(14,0),
	"P_CONT_NO" VARCHAR2(45),
	"P_CONT_DATE" DATE,
	"REPORT_DATE" DATE,
	"OPEN_DATE" DATE,
	"CR_REPORT_DATE" DATE,
	"CR_OPEN_DATE" DATE,
	"CR_NOT_FOUND" NUMBER(1,0) DEFAULT 0,
	"CR_CREDIT_ID" NUMBER,
	"CREDITOR_ID" NUMBER
   )

 CREATE TABLE "CORE"."LX_MATUR_ACTUAL_DATE_MISM"
   (	"CREDIT_ID" NUMBER(14,0),
	"P_CONT_NO" VARCHAR2(45),
	"P_CONT_DATE" DATE,
	"CONT_MATURITY_DATE" DATE,
	"ACTUAL_ISSUE_DATE" DATE,
	"CREDITOR_ID" NUMBER,
	"CR_MATURITY_DATE" DATE,
	"CR_ISSUE_DATE" DATE,
	"CR_NOT_FOUND" NUMBER(1,0) DEFAULT 0
   )

   CREATE TABLE "CORE"."LX_MATURITY_DATE_MISM"
   (	"CREDIT_ID" NUMBER(14,0),
	"P_CONT_NO" VARCHAR2(45),
	"P_CONT_DATE" DATE,
	"MATURITY_DATE" DATE,
	"CREDITOR_ID" NUMBER,
	"CR_P_CONT_DATE" DATE,
	"CR_MATURITY_DATE" DATE,
	"CR_NOT_FOUND" NUMBER(1,0) DEFAULT 0,
	"P_CONT_ID" NUMBER
   )

   CREATE TABLE "CORE"."LX_PLEDGE_ABSENSE"
   (	"CREDIT_ID" NUMBER(14,0),
	"P_CONT_NO" VARCHAR2(1024),
	"P_CONT_DATE" DATE,
	"CREDITOR_ID" NUMBER,
	"CR_NOT_FOUND" NUMBER(1,0) DEFAULT 0,
	"CR_PLEDGE_COUNT" NUMBER
   )

   CREATE TABLE "CORE"."LX_PLEDGE_NO_ABSENSE"
   (	"PLEDGE_ID" NUMBER(14,0),
	"PL_CONTRACT" VARCHAR2(1024),
	"PL_TYPE_CODE" VARCHAR2(1024),
	"PLEDGES_ID" NUMBER(14,0),
	"CREDIT_ID" NUMBER(14,0),
	"REPORT_DATE" DATE,
	"P_CONT_NO" VARCHAR2(1024),
	"P_CONT_DATE" DATE,
	"CREDITOR_ID" NUMBER,
	"CR_PL_CONTRACT" VARCHAR2(1024),
	"CR_PL_TYPE_CODE" VARCHAR2(1024),
	"CR_NOT_FOUND" NUMBER(1,0) DEFAULT 0
   )

 CREATE TABLE "CORE"."LX_PLEDGE_SUM_ABSENSE"
   (	"PLEDGE_TYPE_ID" NUMBER,
	"PLEDGE_ID" NUMBER(14,0),
	"PL_VALUE" NUMBER(17,3),
	"PL_TYPE_CODE" VARCHAR2(1024),
	"PLEDGES_ID" NUMBER(14,0),
	"CREDIT_ID" NUMBER(14,0),
	"REPORT_DATE" DATE,
	"P_CONT_NO" VARCHAR2(1024),
	"P_CONT_DATE" DATE,
	"CREDITOR_ID" NUMBER,
	"CR_PL_VALUE" NUMBER(17,3),
	"CR_PL_TYPE_CODE" VARCHAR2(1024),
	"CR_NOT_FOUND" NUMBER(1,0) DEFAULT 0
   )

   CREATE TABLE "CORE"."LX_PROLONGATION_DATE_MISM"
   (	"CREDIT_ID" NUMBER(14,0),
	"P_CONT_NO" VARCHAR2(45),
	"P_CONT_DATE" DATE,
	"PROLONGATION_DATE" DATE,
	"CREDITOR_ID" NUMBER,
	"CR_PROLONGATION_DATE" DATE,
	"CR_NOT_FOUND" NUMBER(1,0) DEFAULT 0,
	"P_CONT_ID" NUMBER,
	"CONT_MATURITY_DATE" DATE,
	"CR_CONT_MATURITY_DATE" DATE
   )


  CREATE TABLE "CORE"."LX_ORGANIZATION_HEAD"
   (	"HEAD_ID" NUMBER(14,0),
	"MIDNAME" VARCHAR2(1024 BYTE),
	"LASTNAME" VARCHAR2(1024 BYTE),
	"FIRSTNAME" VARCHAR2(1024 BYTE),
	"LANG" VARCHAR2(1024 BYTE),
	"ORGINFO_ID" NUMBER,
	"SUBJECT_ID" NUMBER,
	"REPORT_DATE" DATE
   )