package com.bsbnb.creditregistry.portlets.queue.thread;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.3-b01- Generated
 * source version: 2.2
 *
 */
@WebServiceClient(name = "CreditReceiver", targetNamespace = "http://www.bsbnb.kz/creditregistry/receiver/ws", wsdlLocation = "http://192.168.0.57:8282/CreditReceiver/receiveCredits?wsdl")
public class CreditReceiver
        extends Service {

    private final static QName CREDITRECEIVER_QNAME = new QName("http://www.bsbnb.kz/creditregistry/receiver/ws", "CreditReceiver");

    public CreditReceiver(URL wsdlLocation) {
        super(wsdlLocation, CREDITRECEIVER_QNAME);
    }

    /**
     *
     * @return returns ReceiveCredits
     */
    @WebEndpoint(name = "CreditReceiverPort")
    public ReceiveCredits getCreditReceiverPort() {
        return super.getPort(new QName("http://www.bsbnb.kz/creditregistry/receiver/ws", "CreditReceiverPort"), ReceiveCredits.class);
    }
}
