package com.bsbnb.creditregistry.portlets.queue.thread;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.3-b01- Generated
 * source version: 2.2
 *
 */
@WebService(name = "receiveCredits", targetNamespace = "http://www.bsbnb.kz/creditregistry/receiver/ws")
public interface ReceiveCredits {

    /**
     *
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "receiveZippedXmlWithoutInputInfo", targetNamespace = "http://www.bsbnb.kz/creditregistry/receiver/ws", className = "kz.bsbnb.creditregistry.receiver.ws.ReceiveZippedXmlWithoutInputInfo")
    @Action(input = "http://www.bsbnb.kz/creditregistry/receiver/ws/receiveCredits/receiveZippedXmlWithoutInputInfo")
    public void receiveZippedXmlWithoutInputInfo(
            @WebParam(name = "arg0", targetNamespace = "") long arg0,
            @WebParam(name = "arg1", targetNamespace = "") byte[] arg1,
            @WebParam(name = "arg2", targetNamespace = "") String arg2,
            @WebParam(name = "arg3", targetNamespace = "") Long arg3);

    /**
     *
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "receiveZippedXml", targetNamespace = "http://www.bsbnb.kz/creditregistry/receiver/ws", className = "kz.bsbnb.creditregistry.receiver.ws.ReceiveZippedXml")
    @Action(input = "http://www.bsbnb.kz/creditregistry/receiver/ws/receiveCredits/receiveZippedXml")
    public void receiveZippedXml(
            @WebParam(name = "arg0", targetNamespace = "") byte[] arg0,
            @WebParam(name = "arg1", targetNamespace = "") String arg1,
            @WebParam(name = "arg2", targetNamespace = "") Long arg2);
}