package com.bsbnb.creditregistry.portlets.queue.ui;

/**
 *
 * @author Aidar.Myrzahanov
 */
public enum Localization {

    EXPORT_TO_XLS_CAPTION("EXPORT-TO-XLS-BUTTON-CAPTION"),
    CAPTION_TEXT("CAPTION-TEXT"),
    REFRESH("REFRESH"),
    LOAD("LOAD"),
    QUEUE_TAB_NAME("QUEUE-TAB-NAME"),
    ADMIN_TAB_NAME("ADMIN-TAB-NAME"),
    START_QUEUE_PROCESSING("START-QUEUE-PROCESSING"),
    STOP_QUEUE_PROCESSING("STOP-QUEUE-PROCESSING"),
    CHRONOLOGICAL_ORDER_DESCRIPTION("CHRONOLOGICAL-ORDER-DESCRIPTION"),
    CYCLE_ORDER_DESCRIPTION("CYCLE-ORDER-DESCRIPTION"),
    MINIMUM_WEIGHT_ORDER_DESCRIPTION("MINIMUM-WEIGHT-ORDER-DESCRIPTION"),
    ORDER_COMBOBOX_CAPTION("ORDER_COMBOBOX_CAPTION"),
    SAVE("SAVE"),
    SETTINGS_SAVED_MESSAGE("SETTINGS-SAVED-MESSAGE"),
    QUEUE_PROCESSING_STARTED("QUEUE-PROCESSING-STARTED"),
    QUEUE_PROCESSING_STOPPED("QUEUE-PROCESSING-STOPPED"),
    PRIORITY_CREDITORS_SELECT_CAPTION("PRIORITY-CREDITORS-SELECT-CAPTION"),
    SHOW_PREVIEW_BUTTON_CAPTION("SHOW-PREVIEW-BUTTON-CAPTION"),
    REMOVE_FROM_QUEUE_BUTTON_HINT("REMOVE-FROM-QUEUE-BUTTON-HINT"),
    INPUT_INFO_SHOULD_BE_IN_QUEUE_TO_UPDATE_STATUS("INPUT-INFO-SHOULD-BE-IN-QUEUE-TO-UPDATE-STATUS"),
    INPUT_INFO_REMOVED_FROM_QUEUE("INPUT-INFO-REMOVED-FROM-QUEUE"),
    INPUT_INFO_REMOVAL_CONFIRMATION_TEXT("INPUT-INFO-REMOVAL-CONFIRMATION-TEXT"),
    INPUT_INFOS_REMOVAL_CONFIRMATION_TEXT("INPUT-INFOS-REMOVAL-CONFIRMATION-TEXT"),
    INPUT_INFO_REMOVAL_CONFIRMATION_CAPTION("INPUT-INFO-REMOVAL-CONFIRMATION-CAPTION"),
    FILES_TAB_CAPTION("FILES-TAB-CAPTION"),
    SUMMARY_TAB_CAPTION("SUMMARY-TAB-CAPTION"),
    SUMMARY_HEADER("SUMMARY-HEADER"),
    SUMMARY_TOTAL_HEADER("SUMMARY-TOTAL-HEADER"),
    QUEUE_IS_EMPTY("QUEUE-IS-EMPTY"),
    REMOVE_FILES_FROM_QUEUE_BUTTON_CAPTION("REMOVE-FILES-FROM-QUEUE-BUTTON-CAPTION"),
    NO_FILES_TO_REMOVE_MESSAGE_CAPTION("NO-FILES-TO-REMOVE-MESSAGE-CAPTION"),
    NO_FILES_TO_REMOVE_MESSAGE_TEXT("NO-FILES-TO-REMOVE-MESSAGE-TEXT"), 
    AUTO_UPDATE("AUTO-UPDATE"),
    REPORT_DATE_CAPTION("REPORT_DATE_CAPTION");
    private final String key;

    private Localization(String key) {
        this.key = key;
    }

    public String getKey() {
        return key;
    }
}
