/*  */

CREATE USER CORE_
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
PROFILE DEFAULT;

GRANT CONNECT TO CORE_;
GRANT RESOURCE TO CORE_;
GRANT CREATE ANY INDEX TO CORE_;
GRANT CREATE ANY TABLE TO CORE_;
GRANT CREATE TABLE TO CORE_;
GRANT CREATE USER TO CORE_;
GRANT CREATE VIEW TO CORE_;
GRANT EXECUTE ANY PROCEDURE TO CORE_;
GRANT UNLIMITED TABLESPACE TO CORE_;



