/*  */

CREATE USER C##CORE IDENTIFIED BY CORE
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
PROFILE DEFAULT;

GRANT CONNECT TO C##CORE;
GRANT RESOURCE TO C##CORE;
GRANT CREATE ANY INDEX TO C##CORE;
GRANT CREATE ANY TABLE TO C##CORE;
GRANT CREATE TABLE TO C##CORE;
GRANT CREATE USER TO C##CORE;
GRANT CREATE VIEW TO C##CORE;
GRANT EXECUTE ANY PROCEDURE TO C##CORE;
GRANT UNLIMITED TABLESPACE TO C##CORE;



