package kz.bsbnb.usci.portlets.signing;

/**
 *
 * @author Aidar.Myrzahanov
 */
public enum Localization {

    SIGNATURE_IS_NOT_VERIFIED("SIGNATURE-IS-NOT-VERIFIED"),
    SIGNATURE_IS_OVERDUE("SIGNATURE-IS_OVERDUE"),
    SIGNATURE_IS_NOT_ACTIVE_YET("SIGNATURE-IS-NOT-ACTIVE-YET"),
    SIGNATURE_BIN_DOESNT_MATCH("SIGNATURE-BIN-DOESNT-MATCH"),
    UNEXPECTED_EXCEPTION_DURING_SIGNATURE_VALIDATION("UNEXPECTED-EXCEPTION-DURING-SIGNATURE-VALIDATION"),
    SIGNATURE_WITHOUT_BIN("SIGNATURE-WITHOUT-BIN"),
    SUBJECT_ALTERNATIVE_NAME_FIELD_IS_EMPTY("SUBJECT-ALTERNATIVE-NAME-FIELD-IS-EMPTY"),
    BIN_NOT_FOUND_FOR_CREDITOR("BIN-NOT-FOUND-FOR-CREDITOR"),
    WRONG_ROOT_CA_NAME("WRONG-ROOT-CA-NAME"),
    SIGNATURE_IS_EMPTY("SIGNATURE-IS-EMPTY"),
    OCSP_REQUEST_FAILED("OCSP-REQUEST-FAILED"),
    OCSP_STATUS_CHECK_FAILED("OCSP-STATUS-CHECK-FAILED"),
    SIGNATURE_IS_INCORRECT("SIGNATURE-IS-INCORRECT");

    private final String key;

    private Localization(String key) {
        this.key = key;
    }

    public String getKey() {
        return key;
    }
}
